import type { ListeningUnit } from "../types";

/** Listening pool, block B: a second part for each of the four roles. */
export const LISTENING_UNITS_B: ListeningUnit[] = [
  {
    id: "L1-B",
    part: {
      role: "Part 1: a conversation between two people in a social situation",
      context: "An enquiry about joining a cycling club",
      wordCount: 372,
      turns: [
        { speaker: "Ruth", accent: "en-AU", line: "Hartley Cycling Club, Ruth speaking. How can I help?" },
        { speaker: "Caller", accent: "en-US", line: "Hi, I saw your stall at the weekend. I'd like to know about joining." },
        { speaker: "Ruth", accent: "en-AU", line: "Of course. Annual membership is forty five pounds, and that covers everything except race entries." },
        { speaker: "Caller", accent: "en-US", line: "And what do I get for that?" },
        { speaker: "Ruth", accent: "en-AU", line: "Insurance while you're riding with us, a free club jersey, and a discount at the two bike shops in town." },
        { speaker: "Caller", accent: "en-US", line: "When do you ride?" },
        { speaker: "Ruth", accent: "en-AU", line: "Our main ride is on Sundays, starting at nine. There's also a shorter ride on Wednesday evenings in the summer, but most people only come to the Sunday one." },
        { speaker: "Caller", accent: "en-US", line: "Where do you meet?" },
        { speaker: "Ruth", accent: "en-AU", line: "In the museum car park, the one behind the building. It's free on Sundays, which is why we use it." },
        { speaker: "Caller", accent: "en-US", line: "And how fast do you go? I'm not very quick yet." },
        { speaker: "Ruth", accent: "en-AU", line: "Every ride is graded by speed, so there's a slow group and a fast group. The beginners' route is about ten miles, and the fast group does twenty five, but you can change groups whenever you like." },
        { speaker: "Caller", accent: "en-US", line: "Do I need anything special?" },
        { speaker: "Ruth", accent: "en-AU", line: "A helmet, and it has to be worn on every ride. Any kind of bike is fine, though I'd avoid a very old one with thin tyres on the gravel sections." },
        { speaker: "Caller", accent: "en-US", line: "What happens if the weather is terrible?" },
        { speaker: "Ruth", accent: "en-AU", line: "We cancel if it's icy, and we put a message on the club website by seven in the morning. Don't ring the office, because nobody is there on a Sunday." },
        { speaker: "Caller", accent: "en-US", line: "Should I do anything before my first ride?" },
        { speaker: "Ruth", accent: "en-AU", line: "Fill in the form online before you come, so we know who you are and who to contact. It only takes a few minutes, and you can't ride with us until we have it." },
        { speaker: "Caller", accent: "en-US", line: "That sounds easy enough." },
        { speaker: "Ruth", accent: "en-AU", line: "It is. And if you're nervous, come on the first Sunday of the month, when we run a gentle introductory ride with one of the coaches." },
      ],
    },
    questions: [
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Annual membership: £ ____",
        answer: "45",
        alternatives: ["forty five"],
        evidence: { turn: 2, quote: "Annual membership is forty five pounds" },
        trap: "similar_sound",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Membership includes a free club ____",
        answer: "jersey",
        evidence: { turn: 4, quote: "a free club jersey" },
        trap: "none",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Main ride day: ____",
        answer: "Sundays",
        alternatives: ["Sunday"],
        evidence: { turn: 6, quote: "Our main ride is on Sundays" },
        trap: "form_shift",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Meeting point: the ____ car park",
        answer: "museum",
        evidence: { turn: 8, quote: "In the museum car park" },
        trap: "none",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Rides are graded by ____",
        answer: "speed",
        evidence: { turn: 10, quote: "Every ride is graded by speed" },
        trap: "none",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Equipment that must be worn on every ride: a ____",
        answer: "helmet",
        evidence: { turn: 12, quote: "A helmet, and it has to be worn on every ride" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the question below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER.",
        stem: "How long is the beginners' route?",
        answer: "ten miles",
        alternatives: ["10 miles"],
        evidence: { turn: 10, quote: "The beginners' route is about ten miles" },
        trap: "number_shift",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the question below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER.",
        stem: "Where is a cancellation message published?",
        answer: "club website",
        alternatives: ["the club website", "website"],
        evidence: { turn: 13, quote: "we put a message on the club website" },
        trap: "speaker_attribution",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What must a new rider do before joining a ride?",
        options: [
          "Telephone the club office.",
          "Complete an online form.",
          "Buy a club jersey.",
        ],
        answer: "Complete an online form.",
        evidence: { turn: 15, quote: "Fill in the form online before you come" },
        trap: "out_of_scope",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "When is a gentle introductory ride offered?",
        options: [
          "Every Sunday morning.",
          "On the first Sunday of the month.",
          "On Wednesday evenings.",
        ],
        answer: "On the first Sunday of the month.",
        evidence: { turn: 17, quote: "come on the first Sunday of the month" },
        trap: "partly_true",
      },
    ],
  },

  {
    id: "L2-B",
    part: {
      role: "Part 2: a monologue set in a social context",
      context: "A warden's welcome talk at a wetland nature reserve",
      wordCount: 366,
      turns: [
        { speaker: "Warden", accent: "en-AU", line: "Welcome to Marsh End. Before you set off, I'll explain what's here and a few things we ask visitors to do." },
        { speaker: "Warden", accent: "en-AU", line: "The reserve covers two hundred and forty hectares. The visitor centre, where you're standing, was a barn until 2011, and we kept the original roof timbers." },
        { speaker: "Warden", accent: "en-AU", line: "The reedbed on the east side is the reason the reserve exists. It was dug for thatching in the nineteenth century, and it now holds one of the largest heron colonies in the region. We've just finished a new hide there, which you can reach along the boardwalk." },
        { speaker: "Warden", accent: "en-AU", line: "The woodland on the western edge was planted by volunteers last winter: about four thousand saplings, mostly oak and hazel. It will look like a field for another few years, so please don't walk through it." },
        { speaker: "Warden", accent: "en-AU", line: "For birdwatchers, April is the best month by a distance, because the migrants arrive and the reeds are still low enough to see through. In the summer the reeds grow taller than most people, and the birds are heard rather than seen." },
        { speaker: "Warden", accent: "en-AU", line: "Two of the paths close in winter, when the ground is waterlogged. The notices go up at the gate and we update the website the same day." },
        { speaker: "Warden", accent: "en-AU", line: "Dogs are welcome but they must be kept on a lead at all times, including in the meadow, because of the ground nesting birds. We had twelve nests lost last year." },
        { speaker: "Warden", accent: "en-AU", line: "If you find a bird that appears to be injured, please don't pick it up and don't take it to the centre. Ring the number on the sign at the entrance instead, and one of the licensed handlers will come out." },
        { speaker: "Warden", accent: "en-AU", line: "Finally, volunteers meet on the first Saturday of every month at nine. There's no need to book, and no experience is needed. If you'd like to help with the survey work rather than the practical tasks, speak to me afterwards." },
      ],
    },
    questions: [
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Size of the reserve: ____ hectares",
        answer: "240",
        alternatives: ["two hundred and forty"],
        evidence: { turn: 1, quote: "covers two hundred and forty hectares" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "The visitor centre was formerly a ____",
        answer: "barn",
        evidence: { turn: 1, quote: "the visitor centre, where you're standing, was a barn" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Best month for birdwatching: ____",
        answer: "April",
        evidence: { turn: 4, quote: "April is the best month by a distance" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Paths close in winter when the ground is ____",
        answer: "waterlogged",
        evidence: { turn: 5, quote: "when the ground is waterlogged" },
        trap: "spelling",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Volunteers meet on the first ____ of each month",
        answer: "Saturday",
        evidence: { turn: 8, quote: "volunteers meet on the first Saturday of every month" },
        trap: "similar_sound",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Dogs must be kept on a ____ at all times",
        answer: "lead",
        alternatives: ["leash"],
        evidence: { turn: 6, quote: "they must be kept on a lead at all times" },
        trap: "none",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What should visitors do with an injured bird?",
        options: [
          "Take it to the visitor centre.",
          "Telephone the number on the entrance sign.",
          "Leave it and move away quietly.",
        ],
        answer: "Telephone the number on the entrance sign.",
        evidence: { turn: 7, quote: "Ring the number on the sign at the entrance instead" },
        trap: "negation_missed",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does the warden say about the new woodland?",
        options: [
          "It is mature enough to walk through.",
          "It was planted by staff.",
          "Visitors should not walk through it yet.",
        ],
        answer: "Visitors should not walk through it yet.",
        evidence: { turn: 3, quote: "please don't walk through it" },
        trap: "partly_true",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct area of the reserve. Choose A, B or C.",
        stem: "A new hide has been built here",
        options: ["the reedbed", "the woodland", "the meadow"],
        answer: "the reedbed",
        evidence: { turn: 2, quote: "We've just finished a new hide there" },
        trap: "none",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct area of the reserve. Choose A, B or C.",
        stem: "Four thousand saplings were planted here",
        options: ["the reedbed", "the woodland", "the meadow"],
        answer: "the woodland",
        evidence: { turn: 3, quote: "about four thousand saplings" },
        trap: "none",
      },
    ],
  },

  {
    id: "L3-B",
    part: {
      role: "Part 3: a conversation between students and a tutor",
      context: "Two students discuss a presentation on shift work and sleep with their tutor",
      wordCount: 388,
      turns: [
        { speaker: "Dr Whitfield", accent: "en-AU", line: "How is the presentation on shift work coming along?" },
        { speaker: "Amina", accent: "en-US", line: "We've read about twenty papers. The finding that surprised us is that it isn't the length of the shift that matters most, it's whether the shift moves forwards or backwards." },
        { speaker: "Tom", accent: "en-US", line: "Rotating backwards, from evening to night to morning, is harder on people than rotating forwards. The body clock shifts more easily in one direction than the other." },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "That's a good line to take. But be careful about how you phrase it. The evidence is strong for alertness and sleep quality, and much weaker for long term health outcomes." },
        { speaker: "Amina", accent: "en-US", line: "So we shouldn't claim it causes disease?" },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "You can say there's an association in the studies you've read. Saying it causes illness goes beyond what a study of this kind can show. And check who funded each study, because a lot of the shift scheduling research was paid for by the industries that use it." },
        { speaker: "Tom", accent: "en-US", line: "For the presentation itself, should we talk about our own experience? I worked nights for a year." },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "Use it as an illustration at the start, but keep it short, and then move to the evidence. Personal accounts persuade an audience but they don't count as data." },
        { speaker: "Amina", accent: "en-US", line: "How long do we have?" },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "Fifteen minutes, and that includes questions. So aim to speak for eleven and leave four. Most groups run over, and it always costs them marks." },
        { speaker: "Tom", accent: "en-US", line: "Should we use slides?" },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "Yes, but fewer than you think. One chart per key point is plenty. If a slide takes more than ten seconds to read, the audience stops listening to you." },
        { speaker: "Amina", accent: "en-US", line: "And the hand-in?" },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "The written summary is due the Friday before, by five in the afternoon, and it's a thousand words, not two thousand. Last year half the group lost marks for length." },
        { speaker: "Tom", accent: "en-US", line: "Where do we hand it in?" },
        { speaker: "Dr Whitfield", accent: "en-AU", line: "Online, through the module page. Please don't email it to me, because I can't record a mark from an email." },
      ],
    },
    questions: [
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What did the students find most surprising in their reading?",
        options: [
          "The length of a shift matters more than its timing.",
          "The direction in which shifts rotate matters most.",
          "Shift workers sleep more than other people.",
        ],
        answer: "The direction in which shifts rotate matters most.",
        evidence: { turn: 1, quote: "it isn't the length of the shift that matters most, it's whether the shift moves forwards or backwards" },
        trap: "reversed_logic",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does Dr Whitfield say about long term health?",
        options: [
          "The evidence for it is weaker than the evidence for alertness.",
          "It has been proved in the studies the students read.",
          "It has never been investigated.",
        ],
        answer: "The evidence for it is weaker than the evidence for alertness.",
        evidence: { turn: 3, quote: "much weaker for long term health outcomes" },
        trap: "negation_missed",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does the tutor advise about funding?",
        options: [
          "It should be ignored as irrelevant.",
          "It makes the research useless.",
          "It should be checked for each study.",
        ],
        answer: "It should be checked for each study.",
        evidence: { turn: 5, quote: "check who funded each study" },
        trap: "out_of_scope",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "How should Tom's personal experience be used?",
        options: [
          "As a short illustration at the start.",
          "As the main evidence for the argument.",
          "It should be left out entirely.",
        ],
        answer: "As a short illustration at the start.",
        evidence: { turn: 7, quote: "Use it as an illustration at the start, but keep it short" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "How should the fifteen minutes be divided?",
        options: [
          "Speak for fifteen and take questions afterwards.",
          "Speak for eleven and leave four for questions.",
          "Speak for twelve and leave three for questions.",
        ],
        answer: "Speak for eleven and leave four for questions.",
        evidence: { turn: 9, quote: "aim to speak for eleven and leave four" },
        trap: "number_shift",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct detail. Choose A, B, C or D.",
        stem: "The written summary is due",
        options: ["the Friday before, by five", "a thousand words", "online, through the module page", "one chart per key point"],
        answer: "the Friday before, by five",
        evidence: { turn: 12, quote: "due the Friday before, by five in the afternoon" },
        trap: "none",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct detail. Choose A, B, C or D.",
        stem: "The required length of the summary",
        options: ["the Friday before, by five", "a thousand words", "online, through the module page", "one chart per key point"],
        answer: "a thousand words",
        evidence: { turn: 12, quote: "it's a thousand words, not two thousand" },
        trap: "number_shift",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct detail. Choose A, B, C or D.",
        stem: "How the summary must be submitted",
        options: ["the Friday before, by five", "a thousand words", "online, through the module page", "one chart per key point"],
        answer: "online, through the module page",
        evidence: { turn: 14, quote: "Online, through the module page" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Write ONE WORD ONLY for each answer.",
        stem: "The body clock shifts more easily in one ____ than the other.",
        answer: "direction",
        evidence: { turn: 2, quote: "The body clock shifts more easily in one direction than the other" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Write ONE WORD ONLY for each answer.",
        stem: "If a slide takes more than ten seconds to read, the audience stops ____.",
        answer: "listening",
        evidence: { turn: 11, quote: "the audience stops listening to you" },
        trap: "form_shift",
      },
    ],
  },

  {
    id: "L4-B",
    part: {
      role: "Part 4: a monologue on an academic subject",
      context: "A lecture on concrete: how it sets, and why it cracks",
      wordCount: 386,
      turns: [
        { speaker: "Lecturer", accent: "en-US", line: "Concrete is the most used material on earth after water, and most people have never thought about how it works. I want to explain the chemistry in five minutes, and then why structures crack." },
        { speaker: "Lecturer", accent: "en-US", line: "When you mix cement with water, the compounds in the cement do not dry out, they react. The main product is a calcium silicate hydrate, usually shortened to C S H, which grows as a tangled mass of very fine crystals, and it is this mass that glues the sand and the stones together." },
        { speaker: "Lecturer", accent: "en-US", line: "The reaction is exothermic, which means it gives out heat, and in a large pour that heat is a problem. The centre of a thick wall may be thirty degrees warmer than the surface, and when the two cool at different rates the concrete cracks before it has carried any load at all." },
        { speaker: "Lecturer", accent: "en-US", line: "The second source of trouble is shrinkage. Concrete contains more water than the reaction needs, and as the surplus evaporates the material contracts. A slab that is restrained by the ground beneath it will crack to relieve the stress, which is why you see cracks at regular intervals in a pavement." },
        { speaker: "Lecturer", accent: "en-US", line: "Now, not all of that is bad. Steel and concrete work well together because they have similar thermal expansion, and steel is strong where concrete is weak. The steel is embedded, and it is protected by the alkaline environment inside the concrete, which keeps the metal passive." },
        { speaker: "Lecturer", accent: "en-US", line: "The protection fails when the concrete carbonates. Carbon dioxide from the air dissolves in the pore water and neutralises the alkalinity, starting at the surface and moving inwards at a few millimetres a year. Once the front reaches the steel, the metal begins to corrode, and because the oxide occupies a larger volume than the metal it replaces, the corrosion pushes the concrete off from the inside. This is why a structure near a coast or on a road that is salted in winter deteriorates faster." },
        { speaker: "Lecturer", accent: "en-US", line: "Roman concrete has been much discussed, because structures built two thousand years ago are still standing. Analysis has found that they used volcanic ash, and that they formed crystals of a mineral that is rare in modern mixes. It is important not to overstate this. Roman concrete was much weaker than ours in compression, and it was used in a different kind of building, without the thin reinforcement that drives our design." },
        { speaker: "Lecturer", accent: "en-US", line: "Modern practice addresses the cracks rather than eliminating them. Reinforcement is placed where the calculations say the structure must crack anyway, so that the cracks are small and evenly distributed rather than few and wide. Supplementary materials, such as fly ash from power stations or slag from steelmaking, react more slowly and generate less heat, which suits massive pours." },
        { speaker: "Lecturer", accent: "en-US", line: "In your handout there's a table of the main deterioration mechanisms and the typical timescale of each. For the coursework, I want you to pick one structure you can visit and identify which mechanism is most likely to affect it, and why. Use the table, but don't simply copy it." },
      ],
    },
    questions: [
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Cement does not dry out, it ____ with water",
        answer: "reacts",
        evidence: { turn: 1, quote: "do not dry out, they react" },
        trap: "negation_missed",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "The reaction gives out heat, so it is described as ____",
        answer: "exothermic",
        evidence: { turn: 2, quote: "The reaction is exothermic" },
        trap: "spelling",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "In a thick wall the centre may be ____ degrees warmer than the surface",
        answer: "30",
        alternatives: ["thirty"],
        evidence: { turn: 2, quote: "may be thirty degrees warmer than the surface" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Carbon dioxide neutralises the alkalinity, a process called ____",
        answer: "carbonation",
        evidence: { turn: 5, quote: "The protection fails when the concrete carbonates" },
        trap: "form_shift",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Carbonation front moves inwards at a few ____ a year",
        answer: "millimetres",
        alternatives: ["millimeters"],
        evidence: { turn: 5, quote: "moving inwards at a few millimetres a year" },
        trap: "spelling",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Corrosion pushes the concrete off because the oxide takes up more ____",
        answer: "volume",
        evidence: { turn: 5, quote: "because the oxide occupies a larger volume than the metal it replaces" },
        trap: "none",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Roman builders used volcanic ____",
        answer: "ash",
        evidence: { turn: 6, quote: "they used volcanic ash" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "Which two materials does the lecturer say work well together?",
        answer: "steel and concrete",
        alternatives: ["concrete and steel"],
        evidence: { turn: 4, quote: "Steel and concrete work well together" },
        trap: "word_limit",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "Where is reinforcement placed according to the calculations?",
        answer: "where it must crack",
        alternatives: ["where the structure must crack"],
        evidence: { turn: 7, quote: "placed where the calculations say the structure must crack anyway" },
        trap: "out_of_scope",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "Which supplementary material from steelmaking generates less heat?",
        answer: "slag",
        evidence: { turn: 7, quote: "slag from steelmaking" },
        trap: "speaker_attribution",
      },
    ],
  },
];
