import type { ListeningUnit } from "../types";

/**
 * Listening pool, block A. One part for each of the four official roles:
 * Part 1 social conversation, Part 2 social monologue, Part 3 educational
 * conversation, Part 4 academic monologue.
 *
 * The transcript lives inside the unit and is never shown before the review
 * stage; the player reads it aloud at the moment of the attempt and the audio
 * is played once, as the real paper requires.
 */
export const LISTENING_UNITS_A: ListeningUnit[] = [
  {
    id: "L1-A",
    part: {
      role: "Part 1: a conversation between two people in a social situation",
      context: "A call to a letting agency about a room in a shared house",
      wordCount: 383,
      turns: [
        { speaker: "Daniel", accent: "en-AU", line: "Good morning, Riverside Lettings, Daniel speaking." },
        { speaker: "Caller", accent: "en-US", line: "Hello. I'm calling about the room you advertised on Ashford Road." },
        { speaker: "Daniel", accent: "en-AU", line: "That's right, forty two Ashford Road, the middle one of three terraced houses. It's a quiet street, just off the main road." },
        { speaker: "Caller", accent: "en-US", line: "And the rent is still five hundred and twenty pounds a month?" },
        { speaker: "Daniel", accent: "en-AU", line: "Five hundred and twenty, yes, and that figure includes water and heating." },
        { speaker: "Caller", accent: "en-US", line: "What about the deposit?" },
        { speaker: "Daniel", accent: "en-AU", line: "Seven hundred and eighty pounds, which works out as a month and a half's rent." },
        { speaker: "Caller", accent: "en-US", line: "And when is the room free?" },
        { speaker: "Daniel", accent: "en-AU", line: "From the second of September. If you needed to move in a few days earlier we could probably arrange that." },
        { speaker: "Caller", accent: "en-US", line: "How many people would I be sharing with?" },
        { speaker: "Daniel", accent: "en-AU", line: "There are three others in the house at the moment, all of them students at the university." },
        { speaker: "Caller", accent: "en-US", line: "Is there anywhere to keep a bicycle?" },
        { speaker: "Daniel", accent: "en-AU", line: "Yes, there's a garage at the back of the house and everyone uses it for bikes. It's locked, so it's safe." },
        { speaker: "Caller", accent: "en-US", line: "Good. And how far is the nearest bus stop?" },
        { speaker: "Daniel", accent: "en-AU", line: "About ten minutes on foot. There's another stop on the main road that's closer, five minutes, but the buses are less frequent from there." },
        { speaker: "Caller", accent: "en-US", line: "Are all the bills covered by the rent?" },
        { speaker: "Daniel", accent: "en-AU", line: "Water and heating are included, but electricity is separate. It's split between the four of you, and it works out at about twenty pounds each a month." },
        { speaker: "Caller", accent: "en-US", line: "And what about parking?" },
        { speaker: "Daniel", accent: "en-AU", line: "I'm afraid there's no parking at the house itself, but there's a car park on Mill Lane that residents can use for very little. Most of our tenants use that." },
        { speaker: "Caller", accent: "en-US", line: "One more thing. Who is the room usually let to?" },
        { speaker: "Daniel", accent: "en-AU", line: "We usually let it to postgraduate students. The others in the house are quiet and they work late, so it suits someone who wants a calm place to study." },
      ],
    },
    questions: [
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Room for rent: 42 ____ Road",
        answer: "Ashford",
        evidence: { turn: 2, quote: "forty two Ashford Road" },
        trap: "similar_sound",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Rent per month: £ ____",
        answer: "520",
        evidence: { turn: 4, quote: "five hundred and twenty pounds a month" },
        trap: "similar_sound",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Deposit required: £ ____",
        answer: "780",
        evidence: { turn: 6, quote: "Seven hundred and eighty pounds" },
        trap: "number_shift",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Available from: 2 ____",
        answer: "September",
        evidence: { turn: 8, quote: "From the second of September" },
        trap: "none",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Number of other tenants: ____",
        answer: "three",
        evidence: { turn: 10, quote: "There are three others in the house" },
        trap: "form_shift",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Bicycle storage: in the ____",
        answer: "garage",
        evidence: { turn: 12, quote: "there's a garage at the back of the house" },
        trap: "none",
      },
      {
        type: "form_completion",
        group: "form",
        instruction: "Complete the form below. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Nearest bus stop: ____ minutes on foot",
        answer: "ten",
        alternatives: ["10"],
        evidence: { turn: 14, quote: "About ten minutes on foot" },
        trap: "number_shift",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the question below. Write NO MORE THAN TWO WORDS.",
        stem: "Which bill is not covered by the rent?",
        answer: "electricity",
        evidence: { turn: 16, quote: "electricity is separate" },
        trap: "speaker_attribution",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does Daniel say about parking?",
        options: [
          "There is space for one car at the house.",
          "Residents can use a car park nearby for a small charge.",
          "Permits are available from the university.",
        ],
        answer: "Residents can use a car park nearby for a small charge.",
        evidence: { turn: 18, quote: "there's a car park on Mill Lane that residents can use for very little" },
        trap: "negation_missed",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "Who is the room usually let to?",
        options: [
          "First year students who want to be social.",
          "Postgraduate students who want a quiet place.",
          "People who work in the city centre.",
        ],
        answer: "Postgraduate students who want a quiet place.",
        evidence: { turn: 20, quote: "We usually let it to postgraduate students" },
        trap: "word_match",
      },
    ],
  },

  {
    id: "L2-A",
    part: {
      role: "Part 2: a monologue set in a social context",
      context: "A talk to new students about how the university library works",
      wordCount: 371,
      turns: [
        { speaker: "Speaker", accent: "en-US", line: "Welcome to the main library. I'll take ten minutes to explain how the building works, and then my colleagues will show you around." },
        { speaker: "Speaker", accent: "en-US", line: "We open at eight every weekday morning, and at ten at weekends. We close at eleven at night during term time, and at six in the vacation." },
        { speaker: "Speaker", accent: "en-US", line: "The ground floor holds the café and four group study rooms. Food and drink are allowed in the café only. Please don't bring them into the rest of the building, because spills damage the collections." },
        { speaker: "Speaker", accent: "en-US", line: "The main collection is on the second floor. The third floor is the silent floor: no talking at all, and phones must be off rather than on silent. It's the busiest part of the building during the exam period, so arrive early if you want a desk." },
        { speaker: "Speaker", accent: "en-US", line: "The basement holds the archive and the older bound journals. You can use them, but you need to ask at the desk and someone will fetch them for you. They don't leave the building." },
        { speaker: "Speaker", accent: "en-US", line: "Borrowing limits depend on who you are. Undergraduates may borrow up to twelve items at a time. Postgraduates and staff may borrow twenty. Everything you borrow has a standard loan period of twenty one days, and it renews automatically unless someone else has reserved the item." },
        { speaker: "Speaker", accent: "en-US", line: "Group study rooms are popular, so they have to be booked. You can book up to two hours in advance, and for a maximum of three hours at a time." },
        { speaker: "Speaker", accent: "en-US", line: "When you've finished with an item, you can hand it to a person at the desk, or put it in the returns chute beside the main doors if the desk is closed." },
        { speaker: "Speaker", accent: "en-US", line: "If something is late, don't panic. You'll get an email reminder first, and a charge only starts a week after that. We would much rather have the book back than have your money." },
        { speaker: "Speaker", accent: "en-US", line: "One last thing. There's a workshop every Wednesday at four on finding sources for your subject. It's free, it's in the group study room on the ground floor, and you don't need to book." },
      ],
    },
    questions: [
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Weekday opening time: ____ in the morning",
        answer: "eight",
        alternatives: ["8"],
        evidence: { turn: 1, quote: "We open at eight every weekday morning" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Silent floor: the ____ floor",
        answer: "third",
        evidence: { turn: 3, quote: "The third floor is the silent floor" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Undergraduate borrowing limit: ____ items",
        answer: "twelve",
        alternatives: ["12"],
        evidence: { turn: 5, quote: "Undergraduates may borrow up to twelve items" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Standard loan period: ____ days",
        answer: "twenty one",
        alternatives: ["21", "twenty-one"],
        evidence: { turn: 5, quote: "a standard loan period of twenty one days" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Group rooms: book up to ____ hours in advance",
        answer: "two",
        alternatives: ["2"],
        evidence: { turn: 6, quote: "You can book up to two hours in advance" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Return items at the ____ beside the main doors",
        answer: "chute",
        evidence: { turn: 7, quote: "put it in the returns chute beside the main doors" },
        trap: "spelling",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does the speaker say about food and drink?",
        options: [
          "They are allowed anywhere on the ground floor.",
          "They are allowed in the café only.",
          "They are not allowed in the building at all.",
        ],
        answer: "They are allowed in the café only.",
        evidence: { turn: 2, quote: "Food and drink are allowed in the café only" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What happens if an item is returned late?",
        options: [
          "A charge is made immediately.",
          "Borrowing rights are suspended.",
          "An email reminder is sent first.",
        ],
        answer: "An email reminder is sent first.",
        evidence: { turn: 8, quote: "You'll get an email reminder first" },
        trap: "partly_true",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct floor. Choose A, B, C or D for each answer.",
        stem: "The archive and older journals",
        options: ["the ground floor", "the second floor", "the third floor", "the basement"],
        answer: "the basement",
        evidence: { turn: 4, quote: "The basement holds the archive and the older bound journals" },
        trap: "none",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each item with the correct floor. Choose A, B, C or D for each answer.",
        stem: "The main collection",
        options: ["the ground floor", "the second floor", "the third floor", "the basement"],
        answer: "the second floor",
        evidence: { turn: 3, quote: "The main collection is on the second floor" },
        trap: "none",
      },
    ],
  },

  {
    id: "L3-A",
    part: {
      role: "Part 3: a conversation between students and a tutor",
      context: "Two students and their tutor plan a project on food waste in campus cafeterias",
      wordCount: 398,
      turns: [
        { speaker: "Dr Osei", accent: "en-AU", line: "So, you want to study food waste in the campus cafeterias. Tell me what you've decided so far." },
        { speaker: "Lena", accent: "en-US", line: "We thought we would weigh the waste from one cafeteria for a fortnight, then compare it with the second cafeteria, which serves the same food but has a different layout." },
        { speaker: "Dr Osei", accent: "en-AU", line: "That's a sensible pairing, because it holds the menu constant. What are you actually going to measure?" },
        { speaker: "Marcus", accent: "en-US", line: "Total weight, and we'll separate it into food that was served and not eaten, and food that was prepared but never served. The second category is usually the bigger one, from what we've read." },
        { speaker: "Dr Osei", accent: "en-AU", line: "Good, and that distinction will be the most interesting part of your report. But weigh everything at the same time of day, otherwise the comparison is worthless." },
        { speaker: "Lena", accent: "en-US", line: "We'll weigh at the end of the lunch service, every weekday." },
        { speaker: "Dr Osei", accent: "en-AU", line: "Weekdays only is fine. Now, what about the permissions? You can't just put scales in a kitchen." },
        { speaker: "Marcus", accent: "en-US", line: "We've asked the catering manager, and she's happy as long as we don't interfere with the staff. She did ask us to avoid the morning, because that's when deliveries arrive." },
        { speaker: "Dr Osei", accent: "en-AU", line: "Then use the afternoon. And you'll need a letter from me for the ethics committee, which takes about a week, so submit that today rather than next month." },
        { speaker: "Lena", accent: "en-US", line: "Should we interview the students as well?" },
        { speaker: "Dr Osei", accent: "en-AU", line: "I'd leave interviews out of it for now. It's a lot of extra work, and the ethics approval for interviews takes much longer. Keep the first study to the numbers, and add interviews next term if the results are interesting." },
        { speaker: "Marcus", accent: "en-US", line: "And what do we do about the days when the cafeteria is closed?" },
        { speaker: "Dr Osei", accent: "en-AU", line: "Record them as missing data, and say so clearly. Don't estimate what the waste would have been. If a day is missing, it's missing." },
        { speaker: "Lena", accent: "en-US", line: "Where should we present the results?" },
        { speaker: "Dr Osei", accent: "en-AU", line: "The undergraduate research conference in April is the obvious place, and the deadline for abstracts is the first of March. That gives you plenty of time if you start the weighing in October." },
      ],
    },
    questions: [
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "Why does Dr Osei approve of comparing the two cafeterias?",
        options: [
          "They are the same size.",
          "They serve the same food but are laid out differently.",
          "One of them is much busier than the other.",
        ],
        answer: "They serve the same food but are laid out differently.",
        evidence: { turn: 1, quote: "serves the same food but has a different layout" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "Which category do the students expect to be larger?",
        options: [
          "Food served but not eaten.",
          "Food prepared but never served.",
          "Food taken away and eaten elsewhere.",
        ],
        answer: "Food prepared but never served.",
        evidence: { turn: 3, quote: "The second category is usually the bigger one" },
        trap: "word_match",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What restriction did the catering manager place on the students?",
        options: [
          "They must not weigh food in the afternoon.",
          "They must avoid the morning.",
          "They must wear kitchen clothing.",
        ],
        answer: "They must avoid the morning.",
        evidence: { turn: 7, quote: "She did ask us to avoid the morning, because that's when deliveries arrive" },
        trap: "reversed_logic",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "What does Dr Osei advise about interviews?",
        options: [
          "They should be added to this study immediately.",
          "They should be left out of the first study.",
          "They are more useful than weighing.",
        ],
        answer: "They should be left out of the first study.",
        evidence: { turn: 9, quote: "I'd leave interviews out of it for now" },
        trap: "negation_missed",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B or C.",
        stem: "How should closed days be handled?",
        options: [
          "Estimate the waste from the days either side.",
          "Move the measurement to the next open day.",
          "Record them as missing data.",
        ],
        answer: "Record them as missing data.",
        evidence: { turn: 11, quote: "Record them as missing data, and say so clearly" },
        trap: "out_of_scope",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each action with the correct deadline or timing. Choose A, B, C or D.",
        stem: "Submitting the letter to the ethics committee",
        options: ["today", "about a week", "the first of March", "October"],
        answer: "today",
        evidence: { turn: 8, quote: "submit that today rather than next month" },
        trap: "number_shift",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each action with the correct deadline or timing. Choose A, B, C or D.",
        stem: "How long ethics approval takes",
        options: ["today", "about a week", "the first of March", "October"],
        answer: "about a week",
        evidence: { turn: 8, quote: "which takes about a week" },
        trap: "number_shift",
      },
      {
        type: "matching",
        group: "matching",
        instruction: "Match each action with the correct deadline or timing. Choose A, B, C or D.",
        stem: "Deadline for conference abstracts",
        options: ["today", "about a week", "the first of March", "October"],
        answer: "the first of March",
        evidence: { turn: 12, quote: "the deadline for abstracts is the first of March" },
        trap: "number_shift",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Write ONE WORD ONLY for each answer.",
        stem: "The students will weigh the waste at the end of the ____ service.",
        answer: "lunch",
        evidence: { turn: 5, quote: "We'll weigh at the end of the lunch service" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Write ONE WORD ONLY for each answer.",
        stem: "The results should be presented at the undergraduate research ____.",
        answer: "conference",
        evidence: { turn: 12, quote: "The undergraduate research conference in April" },
        trap: "form_shift",
      },
    ],
  },

  {
    id: "L4-A",
    part: {
      role: "Part 4: a monologue on an academic subject",
      context: "A lecture on the urban heat island effect",
      wordCount: 392,
      turns: [
        { speaker: "Lecturer", accent: "en-US", line: "Today I want to look at why a city is warmer than the countryside around it. The effect is called the urban heat island, and the temperature difference is usually between two and five degrees at night." },
        { speaker: "Lecturer", accent: "en-US", line: "The first cause is the material cities are made of. Asphalt and concrete absorb solar radiation during the day and release it slowly after sunset, so the city stays warm when the fields have cooled. Compare a dark roof with a field of grass: the roof may reach forty degrees above air temperature, while the grass stays close to it." },
        { speaker: "Lecturer", accent: "en-US", line: "The second cause is geometry. Tall buildings trap radiation between them, because a surface can only lose heat to the sky if it can see the sky. In a narrow street the walls radiate towards each other instead of upwards, so heat stays in the canyon." },
        { speaker: "Lecturer", accent: "en-US", line: "The third cause is the waste heat we produce ourselves. Vehicles, air conditioning units and industry all release energy, and in a dense central district that can add one to two degrees on its own. Notice that air conditioning makes the problem worse in the short term, because it moves heat out of the building and into the street." },
        { speaker: "Lecturer", accent: "en-US", line: "The fourth cause is the loss of vegetation, and the mechanism is not only shade. Plants cool the air by transpiration: water evaporates from the leaves and takes heat with it. A mature tree can move a surprisingly large volume of water in a day, and where the canopy has been removed that cooling stops entirely." },
        { speaker: "Lecturer", accent: "en-US", line: "The consequences are unequal. The effect is strongest at night, which matters because the body recovers from heat during sleep. Districts with less greenery and more paving can be several degrees hotter than leafy districts a few kilometres away, and those districts are often the ones where people cannot afford to run cooling." },
        { speaker: "Lecturer", accent: "en-US", line: "The table in your handout summarises the main interventions and what we know about their performance. Street trees are the most effective per unit of cost in most studies, and they also reduce air pollution and slow rainwater. Cool roofs, painted white or with a reflective coating, are cheap and act immediately, but their benefit is largest during the day, which is when the risk is lowest." },
        { speaker: "Lecturer", accent: "en-US", line: "Water features are popular with designers but the evidence is mixed, because a pond in still air may simply add humidity. Permeable paving helps mainly by allowing evaporation and by recharging groundwater, and its cooling effect is modest." },
        { speaker: "Lecturer", accent: "en-US", line: "The last point is about measurement, and it matters more than it sounds. The difference you report depends on where you put the thermometer. Air temperature measured in a park and in a car park will differ, but so will two measurements in the same street at different heights. Studies that compare a single city station with a single rural station systematically overstate the effect, because a city station is usually sited in a place that is not representative." },
        { speaker: "Lecturer", accent: "en-US", line: "So when you read a headline figure, ask three questions. How many sensors, at what height, and in what kind of surface? A well designed study will use a network of sensors and report the range, not a single number." },
      ],
    },
    questions: [
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "The urban heat island is usually strongest at ____",
        answer: "night",
        evidence: { turn: 0, quote: "the temperature difference is usually between two and five degrees at night" },
        trap: "speaker_attribution",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "In a narrow street, walls radiate heat towards each other, so the heat stays in the ____",
        answer: "canyon",
        evidence: { turn: 2, quote: "heat stays in the canyon" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Plants cool the air by ____, as water evaporates from the leaves",
        answer: "transpiration",
        evidence: { turn: 4, quote: "Plants cool the air by transpiration" },
        trap: "spelling",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
        stem: "Waste heat from vehicles and air conditioning can add up to ____ degrees",
        answer: "two",
        alternatives: ["2"],
        evidence: { turn: 3, quote: "can add one to two degrees on its own" },
        trap: "number_shift",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Street trees: most effective per unit of ____",
        answer: "cost",
        evidence: { turn: 6, quote: "the most effective per unit of cost in most studies" },
        trap: "none",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Cool roofs: benefit is largest during the ____",
        answer: "day",
        evidence: { turn: 6, quote: "their benefit is largest during the day" },
        trap: "reversed_logic",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Write NO MORE THAN TWO WORDS for each answer.",
        stem: "Permeable paving: cooling effect is ____",
        answer: "modest",
        evidence: { turn: 7, quote: "its cooling effect is modest" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "What may a pond in still air add to the atmosphere?",
        answer: "humidity",
        evidence: { turn: 7, quote: "a pond in still air may simply add humidity" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "What does a well designed study report instead of a single number?",
        answer: "the range",
        alternatives: ["range"],
        evidence: { turn: 9, quote: "report the range, not a single number" },
        trap: "word_limit",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Write NO MORE THAN TWO WORDS.",
        stem: "Which measurement location does the lecturer say overstates the effect?",
        answer: "city station",
        alternatives: ["a city station"],
        evidence: { turn: 8, quote: "a city station is usually sited in a place that is not representative" },
        trap: "out_of_scope",
      },
    ],
  },
];
