import type { ReadingMock } from "../types";

/**
 * Reading mock R01. Three passages, 40 questions, 13 + 13 + 14.
 * Original, copyright safe text written for Bandwise. All factual detail is
 * drawn from the public record.
 */
export const R01: ReadingMock = {
  id: "R01",
  title: "Mock 01",
  focus: "Coasts, timekeeping and delivery",
  passages: [
    {
      index: 1,
      title: "Roots that breathe",
      standfirst: "How a mangrove forest meets the sea",
      wordCount: 742,
      paragraphs: [
        "The Sundarbans, spread across the Ganges and Brahmaputra delta where Bangladesh meets India, is the largest single block of mangrove forest on earth, covering roughly ten thousand square kilometres. To a visitor arriving by boat the forest looks almost featureless: a low green wall of leaves that rises and falls with the tide, threaded by channels of brown water. The uniformity is deceptive. At least twenty-six species of mangrove grow here, and each has solved the same problem, living in salt water that would kill an ordinary tree, in a slightly different way.",

        "The first difficulty is the salt itself. Most plants take water in through their roots by osmosis, and sea water holds far too much dissolved salt for that to work. Mangroves answer with a barrier. In species such as sundari, a membrane in the root acts as an ultrafilter: water is admitted while most of the dissolved salts are turned back at the surface. The technique is not perfect, and salt still leaks through. A second mechanism deals with what gets in. Leaves of the Avicennia genus carry salt glands that concentrate the surplus and excrete it, so the surface of the leaf is often visibly crusted with white crystals, which the next heavy shower washes away.",

        "The second difficulty is suffocation. Mangrove mud is waterlogged, fine grained and almost without oxygen, so a root buried in it cannot breathe. The forests answer from above. Many species send up pneumatophores, woody spikes that spring vertically out of the mud and take in air through small pores, then pass it down to the buried root. In others the roots arch into looping props that lift the trunk clear of the water and do the same job. Walk through a mangrove forest at low tide and the ground is a field of these structures, ankle high and knee high, each one a breathing tube.",

        "The third difficulty is reproduction. A seed that simply fell from the tree would sink into mud that gives no purchase, or be carried out to sea. Mangroves have evolved a nursery that floats. In Rhizophora, the seed germinates while it is still attached to the parent, so that what falls is not a seed but a long, cigar shaped seedling, already capable of taking root the moment it lands. Others release lighter propagules that ride the tides for weeks and settle wherever a gap in the canopy offers them light. This is why mangrove forests recover from storms so quickly, and why the same species appear on shorelines hundreds of kilometres apart.",

        "Mangrove roots do not only hold the tree. They hold the coast. The tangle slows the water until the sediment it carries can no longer stay suspended, so it settles among the roots. Over decades the forest builds land, raising a muddy platform above the tide and turning open water into ground that other plants can colonise. When the cyclone Sidr struck Bangladesh in 2007, and Aila followed two years later, settlements behind belts of mangroves recorded far less destruction than exposed ones, and image studies of the delta have found that the width of the forest belt is closely related to how much surge a coastline absorbs. The forest is, in effect, a sea wall that maintains itself.",

        "That self maintenance is now under strain. Upstream diversion of river water has reduced the flow of fresh water into the delta, and the salt front has moved inland, changing which species can survive where. Shrimp ponds cut out of the forest in the 1980s and 1990s removed several hundred square kilometres of trees before courts restricted them. Sea level rise pushes the salinity further upstream every decade. The most common repair, planting seedlings by the thousand, frequently fails, because a species that thrives at the seaward edge will die in the brackish interior and the reverse; restoration has to match the plant to the position on the salinity gradient, which is a slower and more careful job than a mass planting.",
      ],
    },
    {
      index: 2,
      title: "The clock that went to sea",
      standfirst: "Two routes to knowing where you are",
      wordCount: 731,
      paragraphs: [
        "A sailor can find latitude at noon with a sextant and a table, because the height of the sun above the horizon depends on how far north or south the ship is. Longitude is a different matter. Because the earth turns, every east to west position corresponds to a moment in time: local noon arrives four minutes later for each degree you travel west. A navigator who knows the exact time at a fixed reference point, and compares it with local noon on board, can calculate the position. The whole problem therefore reduces to one question. How do you carry an accurate clock across an ocean?",

        "In 1707 a fleet under Admiral Cloudesley Shovell ran aground in fog among the Isles of Scilly after a week of dead reckoning that had put the ships further east than they really were. Losses ran into several ships and well over a thousand men. The disaster gave weight to a campaign for a public reward. The Longitude Act of 1714 offered twenty thousand pounds for a method that could determine longitude to within half a degree, and set up a Board of Longitude to judge the entries. Almost everyone expected the winner to be an astronomer. The alternative, measuring the angle between the moon and a star and looking the answer up in a printed table, needed no machinery and could not lose accuracy through a mechanical fault. Clocks, in the view of most of the Board, were hopeless. A pendulum clock is helpless on a rolling ship, and the metal of any spring or balance changes its dimensions, and so its rate, with every shift in temperature.",

        "John Harrison, a carpenter from Lincolnshire who taught himself clockmaking, disagreed. He attacked the temperature problem directly, combining metals that expand and contract at different rates so that the changes cancelled each other out, and designing an escapement that took its energy from the clock rather than from the pendulum. His first sea clock, known now as H1, was finished in 1735 and tested on a voyage to Lisbon. The second and third followed, growing more complicated as he tried to eliminate every error he could think of, and consuming nineteen years. He then changed approach completely. H4, completed in 1761, was not a machine the size of a wardrobe but a large watch, five inches across. On a voyage to Jamaica it lost about five seconds in eighty one days, an accuracy four times better than the Act demanded.",

        "The Board did not hand over the prize. Its most influential member, the Astronomer Royal Nevil Maskelyne, had published the first Nautical Almanac in 1767, a set of lunar tables that made the astronomical method practical, and he argued that a single watch was inherently less trustworthy than tables anyone could check. Others noted that Maskelyne was also the person who assessed the competition. In 1765 the Board offered ten thousand pounds on condition that Harrison reveal the mechanism of H4 and hand over all four of his timekeepers into its keeping, an arrangement he accepted only under protest. He was never fully paid. His son William took up the case, and in 1772 the king, George the Third, had H5 tested privately at Richmond and then pressed the Board; William received a further eight thousand seven hundred and fifty pounds in 1773. John Harrison died three years later.",

        "What he had demonstrated outlived the argument. By 1800 chronometers were standard equipment on naval vessels and on the merchant ships that followed, made in quantity by two London workshops, those of John Arnold and Thomas Earnshaw. Mechanical chronometers gave way to quartz oscillators in the twentieth century and quartz has now given way to signals from satellites. The underlying principle, however, has not changed. Navigation by time, carried forward from a known starting point, is still how a great deal of the world knows where it is.",
      ],
    },
    {
      index: 3,
      title: "Two degrees of separation",
      standfirst: "The writer argues that vaccine delivery is a logistics problem rather than a scientific one",
      wordCount: 726,
      paragraphs: [
        "A vaccine is a fragile thing. Most of the routine childhood vaccines lose potency if they are frozen, and lose it again if they are allowed to warm past about eight degrees. The window they can survive, in other words, is roughly the same as the window of a domestic refrigerator, and they have to travel from a factory to a clinic in the last kilometre of a country where there may be no reliable electricity at all. It is tempting to treat the resulting failures as a science problem, solvable with a cleverer molecule. The record suggests that they are overwhelmingly a logistics problem, and that logistics is where the money and the attention should go.",

        "Consider what has to happen. A freeze dried vaccine leaves the manufacturer in a vial, is packed into a cold box with conditioned ice packs, travels by air and then by road, is stored in a national or regional cold store, is moved to a district store, then to a health post, and finally into a carrier on a motorbike or on foot. At each transfer the vial may sit in the sun for an hour. The World Health Organization's solution to monitoring this chain is deliberately low technology. A vaccine vial monitor is a small square of heat sensitive film printed on the label. It darkens steadily as it accumulates heat, and when its inner square is darker than the outer circle the vial is discarded, whether or not it still looks cold. One glance at a label replaces a test that would need laboratory equipment.",

        "The cold chain has also had to be rebuilt around power. In places with no grid, a compression refrigerator driven by a diesel generator is both expensive and unreliable, and the fuel is often the first thing to run out. Solar direct drive refrigerators, which hold their temperature through a day of cloud and a night of darkness using a large thermal store and no battery, have replaced tens of thousands of units. Their maintenance depends on a supply of trained technicians and spare parts; a refrigerator that nobody can repair is not a cold chain, it is a delay.",

        "Two episodes show how decisive logistics can be. In the West African Ebola outbreak of 2014 and 2015, the vaccine that was eventually used in trials required storage at about minus seventy degrees, far colder than any routine vaccine, and the response had to invent a portable cold chain almost from nothing, using dry ice and specially made carriers. Five years later, the first covid vaccines presented the same problem at a hundred times the scale. In both cases the scientific question, whether the vaccine worked, was answered well before the practical question of whether it could reach people who needed it.",

        "None of this means the science is finished. A thermostable vaccine that could be stored at room temperature would remove the cold chain entirely, and researchers continue to work on formulations that tolerate heat. But the hundredth vaccine that survives a day in the sun is not what stands between most children and immunisation today. What stands between them is a road that floods, a clinic with a broken refrigerator, a carrier with no ice, and a record system that cannot tell anyone where the doses went. Those are dull problems. They are also the ones that decide the outcome.",

        "There is a further cost that is rarely counted. The refrigerants used in cold chain equipment are themselves potent greenhouse gases, and a national immunisation programme can draw a surprising share of a health ministry's electricity. The shift to solar direct drive reduces both. It is a reminder that in public health the elegant intervention is often the one that removes an entire class of failure rather than the one that adds a new capability.",
      ],
    },
  ],
  questions: [
    {
      n: 1,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use all of them.",
      stem: "Paragraph A",
      options: [
        "A forest with several answers to one problem",
        "Barriers at the root, glands on the leaf",
        "A nursery that floats",
        "Land built by vegetation",
        "Roots that reach up for air",
        "Growing the wrong forest back",
        "A delta without tides",
      ],
      answer: "A forest with several answers to one problem",
      evidence: { paragraph: "A", quote: "each has solved the same problem, living in salt water that would kill an ordinary tree, in a slightly different way" },
      trap: "none",
    },
    {
      n: 2,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use all of them.",
      stem: "Paragraph B",
      options: [
        "A forest with several answers to one problem",
        "Barriers at the root, glands on the leaf",
        "A nursery that floats",
        "Land built by vegetation",
        "Roots that reach up for air",
        "Growing the wrong forest back",
        "A delta without tides",
      ],
      answer: "Barriers at the root, glands on the leaf",
      evidence: { paragraph: "B", quote: "a membrane in the root acts as an ultrafilter ... Leaves of the Avicennia genus carry salt glands" },
      trap: "partly_true",
    },
    {
      n: 3,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use all of them.",
      stem: "Paragraph C",
      options: [
        "A forest with several answers to one problem",
        "Barriers at the root, glands on the leaf",
        "A nursery that floats",
        "Land built by vegetation",
        "Roots that reach up for air",
        "Growing the wrong forest back",
        "A delta without tides",
      ],
      answer: "Roots that reach up for air",
      evidence: { paragraph: "C", quote: "send up pneumatophores, woody spikes that spring vertically out of the mud" },
      trap: "none",
    },
    {
      n: 4,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use all of them.",
      stem: "Paragraph D",
      options: [
        "A forest with several answers to one problem",
        "Barriers at the root, glands on the leaf",
        "A nursery that floats",
        "Land built by vegetation",
        "Roots that reach up for air",
        "Growing the wrong forest back",
        "A delta without tides",
      ],
      answer: "A nursery that floats",
      evidence: { paragraph: "D", quote: "Mangroves have evolved a nursery that floats" },
      trap: "none",
    },
    {
      n: 5,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use all of them.",
      stem: "Paragraph F",
      options: [
        "A forest with several answers to one problem",
        "Barriers at the root, glands on the leaf",
        "A nursery that floats",
        "Land built by vegetation",
        "Roots that reach up for air",
        "Growing the wrong forest back",
        "A delta without tides",
      ],
      answer: "Growing the wrong forest back",
      evidence: { paragraph: "F", quote: "restoration has to match the plant to the position on the salinity gradient" },
      trap: "out_of_scope",
    },
    {
      n: 6,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 1? Write TRUE if the statement agrees with the information, FALSE if the statement contradicts it, NOT GIVEN if there is no information on this.",
      stem: "The Sundarbans is the largest single block of mangrove forest in the world.",
      answer: "TRUE",
      evidence: { paragraph: "A", quote: "is the largest single block of mangrove forest on earth" },
      trap: "none",
    },
    {
      n: 7,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 1? Write TRUE if the statement agrees with the information, FALSE if the statement contradicts it, NOT GIVEN if there is no information on this.",
      stem: "Every mangrove species in the forest keeps salt out in the same way.",
      answer: "FALSE",
      evidence: { paragraph: "A", quote: "each has solved the same problem ... in a slightly different way" },
      trap: "over_generalisation",
    },
    {
      n: 8,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 1? Write TRUE if the statement agrees with the information, FALSE if the statement contradicts it, NOT GIVEN if there is no information on this.",
      stem: "Salt glands are found on sundari trees.",
      answer: "FALSE",
      evidence: { paragraph: "B", quote: "Leaves of the Avicennia genus carry salt glands" },
      trap: "word_match",
    },
    {
      n: 9,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 1? Write TRUE if the statement agrees with the information, FALSE if the statement contradicts it, NOT GIVEN if there is no information on this.",
      stem: "Planting mangroves costs more than building concrete sea walls.",
      answer: "NOT GIVEN",
      evidence: { paragraph: "F", quote: "restoration has to match the plant to the position on the salinity gradient" },
      trap: "over_inference",
    },
    {
      n: 10,
      passage: 1,
      type: "sentence_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "In sundari, a membrane in the root works as an ____, holding back most dissolved salts.",
      answer: "ultrafilter",
      alternatives: ["ultra-filter"],
      evidence: { paragraph: "B", quote: "a membrane in the root acts as an ultrafilter" },
      trap: "none",
    },
    {
      n: 11,
      passage: 1,
      type: "sentence_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Mangrove mud holds very little ____, so roots must reach above the surface to obtain it.",
      answer: "oxygen",
      evidence: { paragraph: "C", quote: "fine grained and almost without oxygen" },
      trap: "none",
    },
    {
      n: 12,
      passage: 1,
      type: "sentence_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Lighter ____ released by some mangroves can travel on the tide for weeks before settling.",
      answer: "propagules",
      evidence: { paragraph: "D", quote: "Others release lighter propagules that ride the tides for weeks" },
      trap: "none",
    },
    {
      n: 13,
      passage: 1,
      type: "sentence_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Because the roots slow the water, sediment settles and new ____ is gradually formed.",
      answer: "land",
      evidence: { paragraph: "E", quote: "the forest builds land" },
      trap: "form_shift",
    },

    {
      n: 14,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "why a pendulum could not be used on a ship",
      options: ["A", "B", "C", "D", "E"],
      answer: "B",
      evidence: { paragraph: "B", quote: "A pendulum clock is helpless on a rolling ship" },
      trap: "none",
    },
    {
      n: 15,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "a ruler who arranged a private test of a timekeeper",
      options: ["A", "B", "C", "D", "E"],
      answer: "D",
      evidence: { paragraph: "D", quote: "the king, George the Third, had H5 tested privately at Richmond" },
      trap: "none",
    },
    {
      n: 16,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "how much time a watch lost during a voyage to Jamaica",
      options: ["A", "B", "C", "D", "E"],
      answer: "C",
      evidence: { paragraph: "C", quote: "On a voyage to Jamaica it lost about five seconds in eighty one days" },
      trap: "number_shift",
    },
    {
      n: 17,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "a naval accident that caused heavy loss of life",
      options: ["A", "B", "C", "D", "E"],
      answer: "B",
      evidence: { paragraph: "B", quote: "Losses ran into several ships and well over a thousand men" },
      trap: "none",
    },
    {
      n: 18,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "the first publication of tables supporting the astronomical method",
      options: ["A", "B", "C", "D", "E"],
      answer: "D",
      evidence: { paragraph: "D", quote: "had published the first Nautical Almanac in 1767" },
      trap: "none",
    },
    {
      n: 19,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
      stem: "the size of the reward offered by an act of parliament",
      options: ["A", "B", "C", "D", "E"],
      answer: "B",
      evidence: { paragraph: "B", quote: "The Longitude Act of 1714 offered twenty thousand pounds" },
      trap: "none",
    },
    {
      n: 20,
      passage: 2,
      type: "tfng",
      group: "Questions 20 to 22",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 2? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Longitude can be worked out from the difference between local time and the time at a fixed reference point.",
      answer: "TRUE",
      evidence: { paragraph: "A", quote: "compares it with local noon on board, can calculate the position" },
      trap: "none",
    },
    {
      n: 21,
      passage: 2,
      type: "tfng",
      group: "Questions 20 to 22",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 2? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Harrison was paid the full twenty thousand pounds before he died.",
      answer: "FALSE",
      evidence: { paragraph: "D", quote: "He was never fully paid" },
      trap: "negation_missed",
    },
    {
      n: 22,
      passage: 2,
      type: "tfng",
      group: "Questions 20 to 22",
      instruction:
        "Do the following statements agree with the information given in Reading Passage 2? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Harrison had a formal education in clockmaking.",
      answer: "NOT GIVEN",
      evidence: { paragraph: "C", quote: "a carpenter from Lincolnshire who taught himself clockmaking" },
      trap: "over_inference",
    },
    {
      n: 23,
      passage: 2,
      type: "summary_completion",
      group: "Questions 23 to 26",
      instruction:
        "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "Harrison approached the problem of temperature by combining metals that expand at different rates, so that their changes ____ (23) each other out.",
      answer: "cancelled",
      alternatives: ["cancel", "cancelled each other"],
      evidence: { paragraph: "C", quote: "so that the changes cancelled each other out" },
      trap: "form_shift",
    },
    {
      n: 24,
      passage: 2,
      type: "summary_completion",
      group: "Questions 23 to 26",
      instruction:
        "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "His first sea clock was finished in 1735 and tested on a voyage to ____ (24).",
      answer: "Lisbon",
      evidence: { paragraph: "C", quote: "tested on a voyage to Lisbon" },
      trap: "none",
    },
    {
      n: 25,
      passage: 2,
      type: "summary_completion",
      group: "Questions 23 to 26",
      instruction:
        "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "The Board required him to reveal the mechanism of H4 and to hand the four timekeepers into its ____ (25).",
      answer: "keeping",
      evidence: { paragraph: "D", quote: "hand over all four of his timekeepers into its keeping" },
      trap: "none",
    },
    {
      n: 26,
      passage: 2,
      type: "summary_completion",
      group: "Questions 23 to 26",
      instruction:
        "Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "By 1800 chronometers were standard equipment, made in quantity by two London ____ (26).",
      answer: "workshops",
      evidence: { paragraph: "E", quote: "made in quantity by two London workshops" },
      trap: "none",
    },

    {
      n: 27,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 27 to 30",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "What is the writer's main point in the first paragraph?",
      options: [
        "Vaccines are too delicate for use in remote areas.",
        "Delivery, rather than the design of the vaccine, causes most failures.",
        "Refrigeration should be removed from the vaccine supply chain.",
        "Most childhood vaccines can safely be frozen.",
      ],
      answer: "Delivery, rather than the design of the vaccine, causes most failures.",
      evidence: { paragraph: "A", quote: "they are overwhelmingly a logistics problem, and that logistics is where the money and the attention should go" },
      trap: "partly_true",
    },
    {
      n: 28,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 27 to 30",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "The vaccine vial monitor is useful because it",
      options: [
        "shows how much heat a vial has been exposed to.",
        "measures the temperature of the cold box.",
        "replaces the need for ice packs entirely.",
        "detects whether a vaccine has been frozen.",
      ],
      answer: "shows how much heat a vial has been exposed to.",
      evidence: { paragraph: "B", quote: "It darkens steadily as it accumulates heat" },
      trap: "out_of_scope",
    },
    {
      n: 29,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 27 to 30",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "What does the writer suggest about solar direct drive refrigerators?",
      options: [
        "They are cheaper to buy than diesel generators but need more fuel.",
        "They remove the need for trained technicians.",
        "Their value depends on local repair and spare parts.",
        "They cannot hold temperature overnight.",
      ],
      answer: "Their value depends on local repair and spare parts.",
      evidence: { paragraph: "C", quote: "a refrigerator that nobody can repair is not a cold chain, it is a delay" },
      trap: "partly_true",
    },
    {
      n: 30,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 27 to 30",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "Why does the writer mention the Ebola and covid episodes?",
      options: [
        "To show that vaccine science was not yet settled.",
        "To show that the practical question of reach was answered later than the scientific one.",
        "To argue that ultra cold storage is unnecessary.",
        "To compare the cost of two public health campaigns.",
      ],
      answer: "To show that the practical question of reach was answered later than the scientific one.",
      evidence: { paragraph: "D", quote: "the scientific question, whether the vaccine worked, was answered well before the practical question" },
      trap: "reversed_logic",
    },
    {
      n: 31,
      passage: 3,
      type: "matching_features",
      group: "Questions 31 to 34",
      instruction:
        "Look at the following statements and the list of items below. Match each statement with the correct item.",
      stem: "It can be checked by looking at a label.",
      options: ["vaccine vial monitor", "diesel generator", "solar direct drive refrigerator", "thermostable vaccine"],
      answer: "vaccine vial monitor",
      evidence: { paragraph: "B", quote: "One glance at a label replaces a test that would need laboratory equipment" },
      trap: "none",
    },
    {
      n: 32,
      passage: 3,
      type: "matching_features",
      group: "Questions 31 to 34",
      instruction:
        "Look at the following statements and the list of items below. Match each statement with the correct item.",
      stem: "Its weak point is often the supply of fuel.",
      options: ["vaccine vial monitor", "diesel generator", "solar direct drive refrigerator", "thermostable vaccine"],
      answer: "diesel generator",
      evidence: { paragraph: "C", quote: "the fuel is often the first thing to run out" },
      trap: "none",
    },
    {
      n: 33,
      passage: 3,
      type: "matching_features",
      group: "Questions 31 to 34",
      instruction:
        "Look at the following statements and the list of items below. Match each statement with the correct item.",
      stem: "It would make the cold chain unnecessary.",
      options: ["vaccine vial monitor", "diesel generator", "solar direct drive refrigerator", "thermostable vaccine"],
      answer: "thermostable vaccine",
      evidence: { paragraph: "E", quote: "A thermostable vaccine that could be stored at room temperature would remove the cold chain entirely" },
      trap: "none",
    },
    {
      n: 34,
      passage: 3,
      type: "matching_features",
      group: "Questions 31 to 34",
      instruction:
        "Look at the following statements and the list of items below. Match each statement with the correct item.",
      stem: "It cuts both electricity use and the emission of greenhouse gases.",
      options: ["vaccine vial monitor", "diesel generator", "solar direct drive refrigerator", "thermostable vaccine"],
      answer: "solar direct drive refrigerator",
      evidence: { paragraph: "F", quote: "The shift to solar direct drive reduces both" },
      trap: "word_match",
    },
    {
      n: 35,
      passage: 3,
      type: "note_completion",
      group: "Questions 35 to 38",
      instruction:
        "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "Safe temperature window for most routine vaccines: not frozen, and not warmer than about ____ (35).",
      answer: "eight degrees",
      alternatives: ["8 degrees", "eight degrees celsius", "8 degrees celsius"],
      evidence: { paragraph: "A", quote: "lose it again if they are allowed to warm past about eight degrees" },
      trap: "form_shift",
    },
    {
      n: 36,
      passage: 3,
      type: "note_completion",
      group: "Questions 35 to 38",
      instruction:
        "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "The film is printed on the ____ (36) of the vial.",
      answer: "label",
      evidence: { paragraph: "B", quote: "a small square of heat sensitive film printed on the label" },
      trap: "none",
    },
    {
      n: 37,
      passage: 3,
      type: "note_completion",
      group: "Questions 35 to 38",
      instruction:
        "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "Solar refrigerators hold temperature through the night using a large ____ (37) and no battery.",
      answer: "thermal store",
      evidence: { paragraph: "C", quote: "using a large thermal store and no battery" },
      trap: "none",
    },
    {
      n: 38,
      passage: 3,
      type: "note_completion",
      group: "Questions 35 to 38",
      instruction:
        "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "The vaccines used in the Ebola trials needed storage at about minus ____ (38) degrees.",
      answer: "seventy",
      alternatives: ["70"],
      evidence: { paragraph: "D", quote: "required storage at about minus seventy degrees" },
      trap: "number_shift",
    },
    {
      n: 39,
      passage: 3,
      type: "short_answer",
      group: "Questions 39 and 40",
      instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
      stem: "Which two things does the writer identify as dull problems that decide the outcome?",
      answer: "roads and records",
      alternatives: ["a road that floods and a record system", "flooding roads and record systems"],
      evidence: { paragraph: "E", quote: "a road that floods ... a record system that cannot tell anyone where the doses went" },
      trap: "over_generalisation",
    },
    {
      n: 40,
      passage: 3,
      type: "short_answer",
      group: "Questions 39 and 40",
      instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
      stem: "What kind of intervention does the writer call elegant at the end of the passage?",
      answer: "the one that removes",
      alternatives: ["one that removes an entire class of failure", "an intervention that removes"],
      evidence: { paragraph: "F", quote: "the elegant intervention is often the one that removes an entire class of failure" },
      trap: "out_of_scope",
    },
  ],
};
