import type { ReadingMock } from "../types";

/** Reading mock R02. Three passages, 40 questions, 13 + 13 + 14. */
export const R02: ReadingMock = {
  id: "R02",
  title: "Mock 02",
  focus: "Water, attention and the designed city",
  passages: [
    {
      index: 1,
      title: "Four taps and a barrage",
      standfirst: "How a city with no hinterland supplies its own water",
      wordCount: 626,
      paragraphs: [
        "Singapore is a small island with no river system worth the name, no aquifer of any size, and a population of well over five million. For most of the twentieth century it bought the greater part of its water from across a narrow strait, under agreements signed while it was still a British colony. Independence in 1965 turned that arrangement from a convenience into a vulnerability. The response, sustained for sixty years, has been to turn the whole island into a catchment and to name four separate sources of supply, so that no single failure can empty the taps.",

        "The first source is local rainfall, and the difficulty is that the island has nowhere to store it. Reservoirs built in the early years covered only half the land surface, so the strategy was widened: drains, canals and rivers were converted into a system that carries storm water into seventeen reservoirs, and the catchment now takes in about two thirds of the island. The second source is imported water, still delivered under the 1962 agreement, which remains in place because the alternative is more expensive, not because the supply is secure.",

        "The third source is the one that surprised visitors. Used water, collected from homes and industry, is treated to a standard far beyond what is required for discharge, then passed through a second stage of microfiltration, reverse osmosis and ultraviolet disinfection. The product is clean enough to be sold to industry as process water and, in small quantities, blended into the reservoirs. It is not simply recycled sewage in the popular sense. Each stage removes a distinct class of contaminant, and the water is tested continuously at more than a hundred points before it leaves the plant. The fourth source is desalination, which is reliable in any weather but consumes several times more energy than the other three, and so is held in reserve, expanding only when the others cannot meet demand.",

        "None of this would work without demand management. Water is priced to reflect its full cost, and a conservation tax is charged on consumption above a household allowance. The result is a domestic consumption figure of about 140 litres per person per day, low by the standards of wealthy cities, though the target is lower still. Leakage is hunted through the network with pressure sensors, because in a system this small an unnoticed leak of a few per cent is a strategic problem rather than a maintenance one.",

        "The most visible piece of the system is a dam across the mouth of the island's largest river. Completed in 2008, it converts a tidal estuary into a freshwater reservoir, and its gates separate salt water from fresh, releasing excess rain at low tide. It also made possible a freshwater lake in the middle of the city, which is now used for recreation, and this is not a side effect: the agency that runs the water system also runs the park, on the reasoning that a population which values a river will not pollute it.",

        "The strategy has limits and the government says so. Energy for desalination is bought at market prices, sea levels are rising, and the imported agreement expires in the middle of this century. What the island has bought is time and options, which is a different thing from security, and it is honest about the difference.",
      ],
    },
    {
      index: 2,
      title: "The half hour that repairs attention",
      standfirst: "What a walk outside does to a tired mind",
      wordCount: 618,
      paragraphs: [
        "Ask people why they walk in a park and most will say it clears their head. For a long time that answer had no experimental support. Then, in the late 1980s, two American researchers, Rachel and Stephen Kaplan, proposed attention restoration theory, which begins with a distinction between two kinds of attention. Directed attention is the effortful kind a driver uses in heavy traffic or a student uses to read a dull page. It is limited, it tires, and when it is depleted people make more errors and find it harder to resist distraction. Fascination, by contrast, is attention that is held without effort, and the theory holds that this second kind, not rest, is what restores the first.",

        "Natural environments are rich in what the Kaplans called soft fascination: moving leaves, water, birds, changes in light that are interesting but undemanding, and that leave room for thought. They also offer a sense of being away, a scale of coherence and order that needs no explanation, and compatibility with what a person actually wants to be doing. Urban streets can supply fascination of a kind, but it is usually hard fascination, urgent and attention consuming, which is why a busy road is tiring even when nothing happens on it.",

        "Testing the theory required a way to measure a tired mind. One widely reported study compared two groups of students who each walked for about an hour. Those who walked through an arboretum performed better afterwards on a backwards digit span task and on a task requiring them to name the colour of a word while ignoring its meaning. Those who walked along a busy road did not improve, and rated the walk as less restorative. A later series of studies measured mood and cognitive performance after shorter exposures of ten to twenty minutes, and found improvements at these durations too.",

        "Physiologists have added a second line of evidence. Walking in a forest or beside water is associated with a drop in heart rate and in the concentration of cortisol in saliva, and with changes in the activity of the nervous system that controls the heart's rhythm. The size of these effects varies between studies, and some researchers argue that the comparison is unfair, because a pleasant urban walk is not the same as a stressful one. What has survived scrutiny is narrower and still useful: a quiet green space, of the kind that most towns already possess, produces a measurable recovery in attention and stress within twenty minutes.",

        "The practical questions are about dose and design. Twenty minutes appears to be enough for a measurable effect and an hour gives more, though the gain flattens. Visible greenery matters more than total park area, and a view of trees from a window has been shown to help hospital recovery, which is why some architects now treat a bed's outlook as a clinical variable. The finding that has most interested city authorities is that the benefit does not require wilderness. A canal path, a small square with mature limes, a hospital courtyard with a bench: any of these will do, provided the water is clean and the traffic is out of earshot.",
      ],
    },
    {
      index: 3,
      title: "Against the seamless city",
      standfirst: "The writer argues that frictionless navigation has a price",
      wordCount: 631,
      paragraphs: [
        "The modern city is being smoothed out, and the smoothest surface in it is information. A visitor arriving in an unfamiliar district no longer has to build a picture of it. A phone is held up, a blue line is followed, and the visitor emerges at the correct door having learned almost nothing about the ground passed over. This is offered as an unqualified improvement, and in one respect it certainly is: nobody is lost any more, and getting lost in an unfamiliar place was never a pleasure to the person doing it. Yet a city whose inhabitants cannot find their way without a device has changed in a way that is rarely examined, and I think for the worse.",

        "The evidence from cognitive science is not in serious dispute. People who navigate actively, making their own decisions about turns, form richer mental maps than people who follow a route mechanically, and the difference persists. Students who follow turn by turn instructions remember less of the layout and are worse at estimating distances afterwards. This is not nostalgia about paper maps. It is a statement about how spatial knowledge is built: it is built by deciding, and being slightly wrong, and correcting.",

        "There is a reasonable objection. A mental map is not obviously valuable to a commuter who covers the same route twice a day, and it would be absurd to demand that everyone wander about in order to learn the bus network. My argument is narrower than a general complaint about technology. What troubles me is design that assumes the device, because such design quietly stops giving the city any of the redundant cues that let a person navigate unaided. A station with no sightline to the exit, a district whose buildings are so uniform that one corner looks like another, a street sign removed because a map application covers it: each of these is small, and together they remove the option of navigating without a battery.",

        "The cost becomes visible when the system fails. When a network outage takes out payment and mapping at once, the people who cope are those who know the shape of the place. The same is true of a city's own staff: emergency responders have long insisted on rehearsing routes by memory precisely because they expect the infrastructure to be gone when they need it. A city that has trained its citizens out of that skill has made a small, avoidable bet against itself.",

        "None of which means that I want turn by turn instructions banned. I use them. The proposal is more modest, and cheaper. Keep the redundant layer. Sign the streets properly even though nobody reads the signs. Put a landmark where a decision has to be made, and make it distinctive enough to be remembered. Preserve sightlines, and let a person see where the river is. Design the ground so that the same journey can be made with the device, or without it, and let the traveller decide how much of the city they wish to know. The argument is not against the map. It is against a city that has stopped working without one.",
      ],
    },
  ],
  questions: [
    {
      n: 1,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below.",
      stem: "Paragraph A",
      options: [
        "Turning an island into a catchment",
        "A supply that is held back because it costs the most",
        "Where the water goes after it has been used",
        "Keeping demand and leaks under control",
        "A structure that changed the city around it",
        "What the strategy does not guarantee",
        "The cheapest water in the world",
      ],
      answer: "Turning an island into a catchment",
      evidence: { paragraph: "A", quote: "has been to turn the whole island into a catchment and to name four separate sources of supply" },
      trap: "partly_true",
    },
    {
      n: 2,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below.",
      stem: "Paragraph B",
      options: [
        "Turning an island into a catchment",
        "A supply that is held back because it costs the most",
        "Where the water goes after it has been used",
        "Keeping demand and leaks under control",
        "A structure that changed the city around it",
        "What the strategy does not guarantee",
        "The cheapest water in the world",
      ],
      answer: "A supply that is held back because it costs the most",
      evidence: { paragraph: "B", quote: "still delivered under the 1962 agreement ... because the alternative is more expensive" },
      trap: "out_of_scope",
    },
    {
      n: 3,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below.",
      stem: "Paragraph C",
      options: [
        "Turning an island into a catchment",
        "A supply that is held back because it costs the most",
        "Where the water goes after it has been used",
        "Keeping demand and leaks under control",
        "A structure that changed the city around it",
        "What the strategy does not guarantee",
        "The cheapest water in the world",
      ],
      answer: "Where the water goes after it has been used",
      evidence: { paragraph: "C", quote: "Used water, collected from homes and industry, is treated" },
      trap: "none",
    },
    {
      n: 4,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below.",
      stem: "Paragraph D",
      options: [
        "Turning an island into a catchment",
        "A supply that is held back because it costs the most",
        "Where the water goes after it has been used",
        "Keeping demand and leaks under control",
        "A structure that changed the city around it",
        "What the strategy does not guarantee",
        "The cheapest water in the world",
      ],
      answer: "Keeping demand and leaks under control",
      evidence: { paragraph: "D", quote: "Water is priced to reflect its full cost ... Leakage is hunted through the network" },
      trap: "none",
    },
    {
      n: 5,
      passage: 1,
      type: "matching_headings",
      group: "Questions 1 to 5",
      instruction:
        "Reading Passage 1 has six paragraphs, A to F. Choose the correct heading for each paragraph from the list of headings below.",
      stem: "Paragraph E",
      options: [
        "Turning an island into a catchment",
        "A supply that is held back because it costs the most",
        "Where the water goes after it has been used",
        "Keeping demand and leaks under control",
        "A structure that changed the city around it",
        "What the strategy does not guarantee",
        "The cheapest water in the world",
      ],
      answer: "A structure that changed the city around it",
      evidence: { paragraph: "E", quote: "It also made possible a freshwater lake in the middle of the city" },
      trap: "none",
    },
    {
      n: 6,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction: "Do the following statements agree with the information in Reading Passage 1? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Singapore has significant natural underground water reserves.",
      answer: "FALSE",
      evidence: { paragraph: "A", quote: "no aquifer of any size" },
      trap: "negation_missed",
    },
    {
      n: 7,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction: "Do the following statements agree with the information in Reading Passage 1? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Imported water is still used partly because other sources cost more.",
      answer: "TRUE",
      evidence: { paragraph: "B", quote: "remains in place because the alternative is more expensive" },
      trap: "reversed_logic",
    },
    {
      n: 8,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction: "Do the following statements agree with the information in Reading Passage 1? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Recycled water is only used by industry.",
      answer: "FALSE",
      evidence: { paragraph: "C", quote: "sold to industry as process water and, in small quantities, blended into the reservoirs" },
      trap: "negation_missed",
    },
    {
      n: 9,
      passage: 1,
      type: "tfng",
      group: "Questions 6 to 9",
      instruction: "Do the following statements agree with the information in Reading Passage 1? Write TRUE, FALSE or NOT GIVEN.",
      stem: "Households in Singapore pay less for water than households in other wealthy cities.",
      answer: "NOT GIVEN",
      evidence: { paragraph: "D", quote: "Water is priced to reflect its full cost" },
      trap: "out_of_scope",
    },
    {
      n: 10,
      passage: 1,
      type: "note_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "The local catchment now takes in about ____ (10) of the island.",
      answer: "two thirds",
      alternatives: ["2/3"],
      evidence: { paragraph: "B", quote: "the catchment now takes in about two thirds of the island" },
      trap: "number_shift",
    },
    {
      n: 11,
      passage: 1,
      type: "note_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "Recycled water is tested at more than a hundred ____ (11) before leaving the plant.",
      answer: "points",
      evidence: { paragraph: "C", quote: "tested continuously at more than a hundred points" },
      trap: "none",
    },
    {
      n: 12,
      passage: 1,
      type: "note_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "Domestic use is about ____ (12) litres per person per day.",
      answer: "140",
      evidence: { paragraph: "D", quote: "about 140 litres per person per day" },
      trap: "number_shift",
    },
    {
      n: 13,
      passage: 1,
      type: "note_completion",
      group: "Questions 10 to 13",
      instruction: "Complete the notes below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
      stem: "The dam at the river mouth was completed in ____ (13).",
      answer: "2008",
      evidence: { paragraph: "E", quote: "Completed in 2008" },
      trap: "none",
    },

    {
      n: 14,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "a study that compared two different walking routes",
      options: ["A", "B", "C", "D", "E"],
      answer: "C",
      evidence: { paragraph: "C", quote: "compared two groups of students who each walked for about an hour" },
      trap: "none",
    },
    {
      n: 15,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "the claim that restoration does not require wild landscape",
      options: ["A", "B", "C", "D", "E"],
      answer: "E",
      evidence: { paragraph: "E", quote: "the benefit does not require wilderness" },
      trap: "none",
    },
    {
      n: 16,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "a criticism of the way some studies set up their comparison",
      options: ["A", "B", "C", "D", "E"],
      answer: "D",
      evidence: { paragraph: "D", quote: "some researchers argue that the comparison is unfair" },
      trap: "none",
    },
    {
      n: 17,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "the idea that restoring attention does not depend on resting",
      options: ["A", "B", "C", "D", "E"],
      answer: "A",
      evidence: { paragraph: "A", quote: "this second kind, not rest, is what restores the first" },
      trap: "reversed_logic",
    },
    {
      n: 18,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "a hospital design decision based on a study finding",
      options: ["A", "B", "C", "D", "E"],
      answer: "E",
      evidence: { paragraph: "E", quote: "some architects now treat a bed's outlook as a clinical variable" },
      trap: "out_of_scope",
    },
    {
      n: 19,
      passage: 2,
      type: "matching_information",
      group: "Questions 14 to 19",
      instruction:
        "Reading Passage 2 has five paragraphs, A to E. Which paragraph contains the following information? You may use any letter more than once.",
      stem: "a distinction between two kinds of attention",
      options: ["A", "B", "C", "D", "E"],
      answer: "A",
      evidence: { paragraph: "A", quote: "a distinction between two kinds of attention" },
      trap: "none",
    },
    {
      n: 20,
      passage: 2,
      type: "sentence_endings",
      group: "Questions 20 to 23",
      instruction:
        "Complete each sentence with the correct ending, A to D, below.",
      stem: "Directed attention is the kind that",
      options: [
        "is held without effort by moving leaves or water.",
        "is limited and becomes depleted with use.",
        "measures cortisol in saliva.",
        "is improved by a busy road if the walk is pleasant.",
      ],
      answer: "is limited and becomes depleted with use.",
      evidence: { paragraph: "A", quote: "It is limited, it tires" },
      trap: "none",
    },
    {
      n: 21,
      passage: 2,
      type: "sentence_endings",
      group: "Questions 20 to 23",
      instruction: "Complete each sentence with the correct ending, A to D, below.",
      stem: "Soft fascination describes attention that",
      options: [
        "is held without effort by moving leaves or water.",
        "is limited and becomes depleted with use.",
        "measures cortisol in saliva.",
        "is improved by a busy road if the walk is pleasant.",
      ],
      answer: "is held without effort by moving leaves or water.",
      evidence: { paragraph: "B", quote: "soft fascination: moving leaves, water, birds, changes in light" },
      trap: "none",
    },
    {
      n: 22,
      passage: 2,
      type: "sentence_endings",
      group: "Questions 20 to 23",
      instruction: "Complete each sentence with the correct ending, A to D, below.",
      stem: "A drop in heart rate after a forest walk",
      options: [
        "is held without effort by moving leaves or water.",
        "is limited and becomes depleted with use.",
        "is one of several physiological findings reported.",
        "proves that the attention theory is correct.",
      ],
      answer: "is one of several physiological findings reported.",
      evidence: { paragraph: "D", quote: "a drop in heart rate and in the concentration of cortisol" },
      trap: "over_inference",
    },
    {
      n: 23,
      passage: 2,
      type: "sentence_endings",
      group: "Questions 20 to 23",
      instruction: "Complete each sentence with the correct ending, A to D, below.",
      stem: "The benefit of a green space appears to depend most on",
      options: [
        "is held without effort by moving leaves or water.",
        "is limited and becomes depleted with use.",
        "is one of several physiological findings reported.",
        "how much greenery is visible rather than how large the space is.",
      ],
      answer: "how much greenery is visible rather than how large the space is.",
      evidence: { paragraph: "E", quote: "Visible greenery matters more than total park area" },
      trap: "word_match",
    },
    {
      n: 24,
      passage: 2,
      type: "summary_completion",
      group: "Questions 24 to 26",
      instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Restoration theory was proposed in the late 1980s by two researchers whose surname was ____ (24).",
      answer: "Kaplan",
      evidence: { paragraph: "A", quote: "Rachel and Stephen Kaplan, proposed attention restoration theory" },
      trap: "spelling",
    },
    {
      n: 25,
      passage: 2,
      type: "summary_completion",
      group: "Questions 24 to 26",
      instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Urban streets tend to supply hard fascination, which is described as urgent and attention ____ (25).",
      answer: "consuming",
      evidence: { paragraph: "B", quote: "it is usually hard fascination, urgent and attention consuming" },
      trap: "none",
    },
    {
      n: 26,
      passage: 2,
      type: "summary_completion",
      group: "Questions 24 to 26",
      instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
      stem: "Shorter exposures of ten to twenty ____ (26) also produced improvements.",
      answer: "minutes",
      evidence: { paragraph: "C", quote: "after shorter exposures of ten to twenty minutes" },
      trap: "none",
    },

    {
      n: 27,
      passage: 3,
      type: "ynng",
      group: "Questions 27 to 30",
      instruction:
        "Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO or NOT GIVEN.",
      stem: "The writer accepts that navigation devices have made getting lost less common.",
      answer: "YES",
      evidence: { paragraph: "A", quote: "in one respect it certainly is: nobody is lost any more" },
      trap: "none",
    },
    {
      n: 28,
      passage: 3,
      type: "ynng",
      group: "Questions 27 to 30",
      instruction:
        "Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO or NOT GIVEN.",
      stem: "The writer believes that turn by turn instructions should be prohibited.",
      answer: "NO",
      evidence: { paragraph: "E", quote: "The argument is not against the map" },
      trap: "negation_missed",
    },
    {
      n: 29,
      passage: 3,
      type: "ynng",
      group: "Questions 27 to 30",
      instruction:
        "Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO or NOT GIVEN.",
      stem: "The writer thinks that people who navigate actively develop better spatial knowledge.",
      answer: "YES",
      evidence: { paragraph: "B", quote: "People who navigate actively ... form richer mental maps" },
      trap: "none",
    },
    {
      n: 30,
      passage: 3,
      type: "ynng",
      group: "Questions 27 to 30",
      instruction:
        "Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO or NOT GIVEN.",
      stem: "The writer believes that design decisions are more important than what travellers choose to do.",
      answer: "NOT GIVEN",
      evidence: { paragraph: "E", quote: "let the traveller decide how much of the city they wish to know" },
      trap: "over_inference",
    },
    {
      n: 31,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 31 to 34",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "In the second paragraph, the writer uses the results of cognitive science to argue that",
      options: [
        "paper maps should be reintroduced into schools.",
        "spatial knowledge is built by making and correcting decisions.",
        "commuters have no need of a mental map.",
        "instructions are remembered better than layouts.",
      ],
      answer: "spatial knowledge is built by making and correcting decisions.",
      evidence: { paragraph: "B", quote: "it is built by deciding, and being slightly wrong, and correcting" },
      trap: "partly_true",
    },
    {
      n: 32,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 31 to 34",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "What is the writer's response to the objection in the third paragraph?",
      options: [
        "The objection is correct but irrelevant to his argument.",
        "He concedes it and narrows his argument to design that assumes a device.",
        "He rejects it because commuters rarely use the same route.",
        "He accepts that street signs are unnecessary.",
      ],
      answer: "He concedes it and narrows his argument to design that assumes a device.",
      evidence: { paragraph: "C", quote: "There is a reasonable objection ... My argument is narrower" },
      trap: "partly_true",
    },
    {
      n: 33,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 31 to 34",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "Why does the writer mention emergency responders?",
      options: [
        "To show that they are unusually skilled at navigation.",
        "To give an example of people who expect the technology to be unavailable.",
        "To argue that cities should employ more of them.",
        "To show that route learning is required by law.",
      ],
      answer: "To give an example of people who expect the technology to be unavailable.",
      evidence: { paragraph: "D", quote: "precisely because they expect the infrastructure to be gone when they need it" },
      trap: "out_of_scope",
    },
    {
      n: 34,
      passage: 3,
      type: "multiple_choice",
      group: "Questions 31 to 34",
      instruction: "Choose the correct letter, A, B, C or D.",
      stem: "What does the writer say about the cost of the current approach?",
      options: [
        "It is mainly financial.",
        "It is visible only when the network fails.",
        "It has been fully measured by researchers.",
        "It is greater than the cost of paper maps.",
      ],
      answer: "It is visible only when the network fails.",
      evidence: { paragraph: "D", quote: "The cost becomes visible when the system fails" },
      trap: "none",
    },
    {
      n: 35,
      passage: 3,
      type: "table_completion",
      group: "Questions 35 to 38",
      instruction: "Complete the table. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "Consequence of following instructions mechanically: poorer memory of the ____ (35).",
      answer: "layout",
      evidence: { paragraph: "B", quote: "remember less of the layout" },
      trap: "none",
    },
    {
      n: 36,
      passage: 3,
      type: "table_completion",
      group: "Questions 35 to 38",
      instruction: "Complete the table. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "Design failure: a station with no sightline to the ____ (36).",
      answer: "exit",
      evidence: { paragraph: "C", quote: "A station with no sightline to the exit" },
      trap: "none",
    },
    {
      n: 37,
      passage: 3,
      type: "table_completion",
      group: "Questions 35 to 38",
      instruction: "Complete the table. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "Design failure: a street sign removed because a ____ (37) covers it.",
      answer: "map application",
      alternatives: ["map app", "mapping application"],
      evidence: { paragraph: "C", quote: "a street sign removed because a map application covers it" },
      trap: "form_shift",
    },
    {
      n: 38,
      passage: 3,
      type: "table_completion",
      group: "Questions 35 to 38",
      instruction: "Complete the table. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
      stem: "The writer's proposal: keep the ____ (38) layer that allows unaided navigation.",
      answer: "redundant",
      evidence: { paragraph: "E", quote: "Keep the redundant layer" },
      trap: "none",
    },
    {
      n: 39,
      passage: 3,
      type: "short_answer",
      group: "Questions 39 and 40",
      instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
      stem: "What kind of landmark does the writer want placed where a decision must be made?",
      answer: "distinctive enough to be remembered",
      alternatives: ["a distinctive one", "distinctive"],
      evidence: { paragraph: "E", quote: "make it distinctive enough to be remembered" },
      trap: "word_limit",
    },
    {
      n: 40,
      passage: 3,
      type: "short_answer",
      group: "Questions 39 and 40",
      instruction: "Answer the questions below. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
      stem: "What does the writer say the argument is not against?",
      answer: "the map",
      evidence: { paragraph: "E", quote: "The argument is not against the map" },
      trap: "negation_missed",
    },
  ],
};
