import type { ReadingUnit } from "../types";

/**
 * Reading passage pool, first block. Each unit is one passage plus its own
 * keyed question set (13 or 14 questions) so it can fill one official slot in
 * any mock configuration.
 */
export const READING_UNITS_A: ReadingUnit[] = [
  {
    id: "P-paper",
    passage: {
      title: "The paper that lasts",
      standfirst: "Why nineteenth century books are falling apart while older ones survive",
      wordCount: 648,
      paragraphs: [
        "A book printed in 1620 is often in better condition than a book printed in 1890. The older volume opens easily, its pages are flexible and slightly cream coloured, and it will survive another century of handling. The later one may crumble at the edge of a page if it is turned too firmly, and its paper is brown throughout, not only at the margins. The explanation is not carelessness or heavy use. It is a change in how paper was made, and the change was made for reasons that seemed entirely sensible at the time.",

        "Until the middle of the nineteenth century, European and American paper was made from rags, mostly linen and cotton. The fibres are long, the material is nearly pure cellulose, and a sheet made from it has almost nothing in it that can react with the cellulose and break it down. The process was slow, and by the 1840s the demand for newsprint and cheap novels had outrun the supply of rags. Manufacturers turned to wood, ground into pulp, which was abundant and cheap. They also needed a way to stop ink from spreading in the watery pulp, and the answer was a sizing of alum and rosin.",

        "Alum is the difficulty. In the presence of moisture, it forms a weak acid, and acid catalyses the hydrolysis of cellulose: the long molecular chains that give paper its strength are cut into shorter ones, which is why brittle paper tears instead of bending. The reaction accelerates as it proceeds, since it produces more acid, and it is not slowed by keeping a book dry, because the moisture inside the fibres is enough. A hundred years of slow reaction leaves a page that looks intact and shatters when handled. Conservators refer to the nineteenth and early twentieth century book stock as the brittle books problem, and it is measured in millions of volumes.",

        "Repair is easier to describe than to carry out. Where a volume is valuable for its annotations or its binding, the paper can be treated with an alkaline solution that neutralises the acid and leaves behind a reserve, so that future acid from the environment is buffered. Mass treatment systems process thousands of books at once in a vacuum chamber, but the equipment is expensive and the treatment cannot restore strength that has already been lost, only stop the loss from continuing. Where the text matters more than the object, the volume is filmed or scanned and the original is retired.",

        "The wider lesson concerns papermaking, not conservation. Since the 1980s, most book paper has been made with an alkaline process and a calcium carbonate filler, which leaves the sheet slightly basic and chemically stable for centuries. A paperback printed this decade rests on better paper, chemically speaking, than a first edition of Dickens. Nobody decided to print durable books on unstable paper; the industry took a sequence of individually reasonable decisions and the result was a body of material that must now be rebuilt or replaced.",
      ],
    },
    questions: [
      {
        type: "matching_headings",
        group: "headings",
        instruction:
          "Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs.",
        stem: "Paragraph A",
        options: [
          "An older book outlasts a newer one",
          "Why rags were replaced by wood",
          "The chemistry that destroys the page",
          "Treating what can still be saved",
          "A lesson about papermaking in general",
          "The cost of preserving rare bindings",
        ],
        answer: "An older book outlasts a newer one",
        evidence: { paragraph: "A", quote: "A book printed in 1620 is often in better condition than a book printed in 1890" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction:
          "Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs.",
        stem: "Paragraph B",
        options: [
          "An older book outlasts a newer one",
          "Why rags were replaced by wood",
          "The chemistry that destroys the page",
          "Treating what can still be saved",
          "A lesson about papermaking in general",
          "The cost of preserving rare bindings",
        ],
        answer: "Why rags were replaced by wood",
        evidence: { paragraph: "B", quote: "demand for newsprint and cheap novels had outrun the supply of rags" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction:
          "Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs.",
        stem: "Paragraph C",
        options: [
          "An older book outlasts a newer one",
          "Why rags were replaced by wood",
          "The chemistry that destroys the page",
          "Treating what can still be saved",
          "A lesson about papermaking in general",
          "The cost of preserving rare bindings",
        ],
        answer: "The chemistry that destroys the page",
        evidence: { paragraph: "C", quote: "acid catalyses the hydrolysis of cellulose" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction:
          "Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs.",
        stem: "Paragraph D",
        options: [
          "An older book outlasts a newer one",
          "Why rags were replaced by wood",
          "The chemistry that destroys the page",
          "Treating what can still be saved",
          "A lesson about papermaking in general",
          "The cost of preserving rare bindings",
        ],
        answer: "Treating what can still be saved",
        evidence: { paragraph: "D", quote: "the paper can be treated with an alkaline solution that neutralises the acid" },
        trap: "partly_true",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction:
          "Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs.",
        stem: "Paragraph E",
        options: [
          "An older book outlasts a newer one",
          "Why rags were replaced by wood",
          "The chemistry that destroys the page",
          "Treating what can still be saved",
          "A lesson about papermaking in general",
          "The cost of preserving rare bindings",
        ],
        answer: "A lesson about papermaking in general",
        evidence: { paragraph: "E", quote: "The wider lesson concerns papermaking, not conservation" },
        trap: "out_of_scope",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Rag paper was made mostly from linen and ____ (5).",
        answer: "cotton",
        evidence: { paragraph: "B", quote: "mostly linen and cotton" },
        trap: "none",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Cheaper fibre introduced in the 1840s: wood ground into ____ (6).",
        answer: "pulp",
        evidence: { paragraph: "B", quote: "turned to wood, ground into pulp" },
        trap: "none",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Sizing added to stop ink spreading: alum and ____ (7).",
        answer: "rosin",
        evidence: { paragraph: "B", quote: "a sizing of alum and rosin" },
        trap: "none",
      },
      {
        type: "table_completion",
        group: "table",
        instruction: "Complete the table. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Alkaline papers from the 1980s use a calcium ____ (8) filler.",
        answer: "carbonate",
        evidence: { paragraph: "E", quote: "a calcium carbonate filler" },
        trap: "word_match",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Keeping a brittle book in a dry room stops the acid reaction.",
        answer: "FALSE",
        evidence: { paragraph: "C", quote: "it is not slowed by keeping a book dry" },
        trap: "negation_missed",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Mass treatment restores the strength that brittle paper has lost.",
        answer: "FALSE",
        evidence: { paragraph: "D", quote: "cannot restore strength that has already been lost" },
        trap: "partly_true",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "What name do conservators give to the problem of unstable nineteenth century book stock?",
        answer: "brittle books",
        evidence: { paragraph: "C", quote: "the brittle books problem" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions below. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "Which Dickens edition does the writer use for comparison?",
        answer: "first edition",
        evidence: { paragraph: "E", quote: "a first edition of Dickens" },
        trap: "out_of_scope",
      },
    ],
  },

  {
    id: "P-silk",
    passage: {
      title: "Silk that beats steel",
      standfirst: "The properties of spider dragline and the difficulty of copying them",
      wordCount: 639,
      paragraphs: [
        "Weight for weight, the silk a garden spider uses to make the outer frame of its web is stronger than steel and tougher than most engineering fibres, including the aramid used in bullet resistant vests. A strand is about five times as strong as a steel filament of the same thickness and absorbs several times more energy before it breaks, which is why a web can stop an insect travelling at speed without tearing. It is also made at room temperature, from water, in a material the spider synthesises itself.",

        "The fibre is a protein, and the spider stores it as a liquid concentrate in a gland. Two families of protein, known as spidroins, dominate: one gives the silk its strength, the other its stretch. Each protein has a long central region built of repeating blocks, ending in sections that assemble with neighbours. When the liquid is drawn through a tapering duct towards a spinneret, three things change at once. The acidity falls, the concentration of salts shifts, and the flow itself aligns the molecules. The result is a solid fibre with stiff crystalline regions, where the chains are packed in sheets, joined by softer regions that can unfold and absorb energy. No industrial process reproduces all three changes together at the speed a spider manages.",

        "The obvious commercial route, farming spiders, does not work. Most orb weavers are territorial and cannibalistic, and they cannot be kept at the densities that silk production would need. The strand is also impossibly fine for handling; a single fibre is about a thousandth of a millimetre across, so a fabric would require an enormous number of metres. Attention therefore moved to biology. Researchers insert the gene for a spidroin into bacteria, yeast, plants or even goats, harvest the protein, and then attempt to spin it. Several companies now produce a silk protein this way and spin it into fibres, some for textiles and some for medical devices.",

        "The properties of the spun product, however, are not yet those of the natural fibre. Recombinant proteins are usually shorter than the natural molecule, so the crystalline regions are smaller, and the spinning process is cruder than a duct a fraction of a millimetre wide. Reported strengths of synthetic silk are typically a fraction of the natural value. The medical applications are less demanding and have advanced further: silk is strong, it degrades slowly, and its breakdown products are amino acids the body already handles, so it has been used for sutures, for scaffolds on which tissue can grow, and for coatings on implants.",

        "Whether the textile industry will ever have silk without spiders is genuinely open. The economics are unforgiving, because a natural fibre produced by a farm animal competes against synthetic polymers made from oil at a fraction of the cost per kilogram. What the work has produced so far is a better understanding of why the natural material works, and a set of medical products with a real market. That is a modest return on thirty years of effort, and it is also how materials science usually proceeds.",
      ],
    },
    questions: [
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "The opening paragraph emphasises that spider silk is",
        options: [
          "easy to produce in quantity.",
          "strong and tough in relation to its weight.",
          "stronger than any synthetic fibre in absolute terms.",
          "produced from a petroleum base.",
        ],
        answer: "strong and tough in relation to its weight.",
        evidence: { paragraph: "A", quote: "Weight for weight ... stronger than steel" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "According to the passage, the fibre forms when",
        options: [
          "the protein is heated inside the gland.",
          "salts are added to a concentrated liquid.",
          "acidity, salt concentration and flow direction change together.",
          "the spider pulls the strand away from the spinneret.",
        ],
        answer: "acidity, salt concentration and flow direction change together.",
        evidence: { paragraph: "B", quote: "The acidity falls, the concentration of salts shifts, and the flow itself aligns the molecules" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "What is the main reason spiders are not farmed for silk?",
        options: [
          "Their silk is too weak to be useful in fabric.",
          "They cannot be kept together in large numbers.",
          "Their glands produce too little protein over a lifetime.",
          "Their silk cannot be wound onto a spool.",
        ],
        answer: "They cannot be kept together in large numbers.",
        evidence: { paragraph: "C", quote: "Most orb weavers are territorial and cannibalistic, and they cannot be kept at the densities" },
        trap: "out_of_scope",
      },
      {
        type: "sentence_endings",
        group: "endings",
        instruction: "Complete each sentence with the correct ending, A to D, below.",
        stem: "The crystalline regions in the fibre are joined by",
        options: [
          "softer regions that unfold and absorb energy.",
          "a coating of salts left by the gland.",
          "shorter molecules made in a laboratory.",
          "sheets of aramid polymer.",
        ],
        answer: "softer regions that unfold and absorb energy.",
        evidence: { paragraph: "B", quote: "joined by softer regions that can unfold and absorb energy" },
        trap: "none",
      },
      {
        type: "sentence_endings",
        group: "endings",
        instruction: "Complete each sentence with the correct ending, A to D, below.",
        stem: "Spider silk is difficult to handle because a single strand is",
        options: [
          "softer regions that unfold and absorb energy.",
          "extremely fine, about a thousandth of a millimetre across.",
          "shorter molecules made in a laboratory.",
          "sheet structure of natural silk.",
        ],
        answer: "extremely fine, about a thousandth of a millimetre across.",
        evidence: { paragraph: "C", quote: "a single fibre is about a thousandth of a millimetre across" },
        trap: "none",
      },
      {
        type: "sentence_endings",
        group: "endings",
        instruction: "Complete each sentence with the correct ending, A to D, below.",
        stem: "Synthetic silk is usually weaker than the natural fibre because recombinant proteins are",
        options: [
          "softer regions that unfold and absorb energy.",
          "extremely fine, about a thousandth of a millimetre across.",
          "shorter, so the crystalline regions are smaller.",
          "produced at high temperature.",
        ],
        answer: "shorter, so the crystalline regions are smaller.",
        evidence: { paragraph: "D", quote: "Recombinant proteins are usually shorter than the natural molecule, so the crystalline regions are smaller" },
        trap: "none",
      },
      {
        type: "sentence_endings",
        group: "endings",
        instruction: "Complete each sentence with the correct ending, A to D, below.",
        stem: "The commercial obstacle to silk textiles is that",
        options: [
          "softer regions that unfold and absorb energy.",
          "extremely fine, about a thousandth of a millimetre across.",
          "shorter, so the crystalline regions are smaller.",
          "oil based polymers cost far less per kilogram.",
        ],
        answer: "oil based polymers cost far less per kilogram.",
        evidence: { paragraph: "E", quote: "competes against synthetic polymers made from oil at a fraction of the cost per kilogram" },
        trap: "word_match",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "The silk fibre is a ____ (8), stored as a liquid concentrate in a gland.",
        answer: "protein",
        evidence: { paragraph: "B", quote: "The fibre is a protein" },
        trap: "none",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "Two families of proteins, known as ____ (9), give it strength and stretch.",
        answer: "spidroins",
        evidence: { paragraph: "B", quote: "Two families of protein, known as spidroins" },
        trap: "spelling",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "The fibre leaves the spider through a ____ (10).",
        answer: "spinneret",
        evidence: { paragraph: "B", quote: "drawn through a tapering duct towards a spinneret" },
        trap: "none",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "Medical uses include sutures, scaffolds and ____ (11) on implants.",
        answer: "coatings",
        evidence: { paragraph: "D", quote: "for coatings on implants" },
        trap: "form_shift",
      },
      {
        type: "matching_features",
        group: "features",
        instruction: "Match each statement with the correct item below.",
        stem: "It breaks down into substances the body already processes.",
        options: ["natural spider silk", "recombinant silk protein", "aramid fibre"],
        answer: "natural spider silk",
        evidence: { paragraph: "D", quote: "its breakdown products are amino acids the body already handles" },
        trap: "none",
      },
      {
        type: "matching_features",
        group: "features",
        instruction: "Match each statement with the correct item below.",
        stem: "It is made by inserting a gene into another organism.",
        options: ["natural spider silk", "recombinant silk protein", "aramid fibre"],
        answer: "recombinant silk protein",
        evidence: { paragraph: "C", quote: "insert the gene for a spidroin into bacteria, yeast, plants or even goats" },
        trap: "none",
      },
    ],
  },

  {
    id: "P-ice",
    passage: {
      title: "Reading the ice",
      standfirst: "What a column drilled from an ice sheet records about the past",
      wordCount: 654,
      paragraphs: [
        "An ice sheet is not a uniform block of frozen water. Snow falls, is buried by later snow, and is compressed until the air between the grains is squeezed out. Every year adds a layer, so a vertical column through the sheet contains a sequence of annual bands, and the deeper the sample, the further back in time it reaches. A core drilled through the Antarctic plateau can carry ice that fell as snow before the last million years of the earth's history had been written.",

        "Three kinds of evidence come out of a single core. The first is in the water itself. Natural water contains a small proportion of molecules in which the ordinary oxygen atom is replaced by the heavier isotope oxygen 18, and the ratio between the heavy and light forms depends on the temperature at which the snow formed. Measuring that ratio down a core therefore gives a temperature record, read as a curve, which is why the graphs produced from Antarctic cores are among the best known images in climate science.",

        "The second kind of evidence is the air. As the layers compress, the old atmosphere is sealed inside bubbles, and those bubbles are a direct sample of the gas that surrounded the planet at the time. There is no other way to measure the carbon dioxide content of the air in the year 100,000 BC: no proxy, no reconstruction, an actual measurement of the ancient atmosphere. The result established that carbon dioxide and temperature have risen and fallen together through several ice ages, and gave a figure for the concentration in the pre industrial atmosphere that has been used in every subsequent discussion.",

        "The third kind is what falls with the snow. Dust blown from deserts, ash from volcanoes and traces of salts from the sea are all preserved in their layer, and ash in particular provides dates, because a large eruption leaves a distinctive chemical fingerprint that can be matched to a tree ring or a historical record. Layers can also be counted directly in the upper part of a core, where the annual banding is still visible, and those counts are what calibrate the rest of the record.",

        "Drilling is technically demanding. Ice at depth behaves like a slow, brittle plastic and will flow and close around the hole unless the borehole is filled with a dense fluid that matches the pressure of the surrounding ice. The deepest sections are prone to cracking as they are brought to the surface, and the cores must be cut and stored at temperatures well below freezing, usually in purpose built freezers that are themselves a permanent cost. The East Antarctic record now extends back about 800,000 years, and drilling continues at sites chosen for the thickness and age of the ice beneath them.",

        "There is a limit, and it is not only technical. At a certain depth the layers are so compressed that the annual signal disappears, and near the base of the sheet the ice is deformed and mixed. Ice that lies on a bed that melts will lose its oldest record entirely. The archive, in other words, is finite, and it is being read at a time when the surface conditions that created it are changing quickly enough that some of the records may not be recoverable from the field at all.",
      ],
    },
    questions: [
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to F. You may use any letter more than once.",
        stem: "how the layers are given absolute dates",
        options: ["A", "B", "C", "D", "E", "F"],
        answer: "D",
        evidence: { paragraph: "D", quote: "ash in particular provides dates" },
        trap: "none",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to F. You may use any letter more than once.",
        stem: "a measurement of the atmosphere that no reconstruction can provide",
        options: ["A", "B", "C", "D", "E", "F"],
        answer: "C",
        evidence: { paragraph: "C", quote: "no proxy, no reconstruction, an actual measurement of the ancient atmosphere" },
        trap: "none",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to F. You may use any letter more than once.",
        stem: "equipment that creates a continuing cost",
        options: ["A", "B", "C", "D", "E", "F"],
        answer: "E",
        evidence: { paragraph: "E", quote: "purpose built freezers that are themselves a permanent cost" },
        trap: "out_of_scope",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to F. You may use any letter more than once.",
        stem: "why the archive does not go back indefinitely",
        options: ["A", "B", "C", "D", "E", "F"],
        answer: "F",
        evidence: { paragraph: "F", quote: "The archive, in other words, is finite" },
        trap: "none",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to F. You may use any letter more than once.",
        stem: "a chemical ratio that stands in for temperature",
        options: ["A", "B", "C", "D", "E", "F"],
        answer: "B",
        evidence: { paragraph: "B", quote: "Measuring that ratio down a core therefore gives a temperature record" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Layers compress until the air between the grains is ____ (6) out.",
        answer: "squeezed",
        evidence: { paragraph: "A", quote: "is squeezed out" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "The heavy isotope used as a temperature signal is oxygen ____ (7).",
        answer: "18",
        alternatives: ["eighteen", "oxygen 18"],
        evidence: { paragraph: "B", quote: "the heavier isotope oxygen 18" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "The bubbles are a direct sample of the ancient ____ (8).",
        answer: "atmosphere",
        evidence: { paragraph: "C", quote: "a direct sample of the gas that surrounded the planet" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "A borehole must be filled with a dense ____ (9) to stop the hole closing.",
        answer: "fluid",
        evidence: { paragraph: "E", quote: "filled with a dense fluid" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Ice core data showed that carbon dioxide and temperature rose and fell together during several ice ages.",
        answer: "TRUE",
        evidence: { paragraph: "C", quote: "carbon dioxide and temperature have risen and fallen together through several ice ages" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Annual layers can be counted throughout the whole length of a core.",
        answer: "FALSE",
        evidence: { paragraph: "F", quote: "At a certain depth the layers are so compressed that the annual signal disappears" },
        trap: "over_generalisation",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Ice cores are the only source of evidence about past temperatures.",
        answer: "NOT GIVEN",
        evidence: { paragraph: "B", quote: "Measuring that ratio down a core therefore gives a temperature record" },
        trap: "over_inference",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "How far back does the East Antarctic record currently extend?",
        answer: "800,000 years",
        alternatives: ["800000 years", "about 800,000 years"],
        evidence: { paragraph: "E", quote: "extends back about 800,000 years" },
        trap: "number_shift",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions below. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "What happens to the oldest ice where the bed beneath it melts?",
        answer: "it loses its record",
        alternatives: ["the record is lost", "loses its oldest record", "loses its record"],
        evidence: { paragraph: "F", quote: "Ice that lies on a bed that melts will lose its oldest record entirely" },
        trap: "word_limit",
      },
    ],
  },
];
