import type { ReadingUnit } from "../types";

/** Reading passage pool, second block. */
export const READING_UNITS_B: ReadingUnit[] = [
  {
    id: "P-ocean",
    passage: {
      title: "Naming the ocean floor",
      standfirst: "How a hand drawn map changed what geologists believed",
      wordCount: 641,
      paragraphs: [
        "For most of the nineteenth century the deep ocean was assumed to be a flat, featureless basin with a shallow shelf around each continent. The evidence was thin because the only way to sample the bottom was to lower a weighted line and measure how much rope went out, a slow method that a rolling ship could ruin. The Challenger expedition of the 1870s took the first systematic soundings across three oceans and found that the bottom was not uniform, but the picture it produced was still a scattering of unconnected points.",

        "The instrument that changed this was the echo sounder, developed during the two world wars, which measures the time a pulse of sound takes to travel to the seabed and back. A ship could now record a continuous profile of the bottom as it steamed. By the early 1950s the oceanographic laboratories were collecting tens of thousands of kilometres of these lines, and the problem shifted from obtaining measurements to making sense of them. The data arrived as a stack of paper curves, each one a slice through the bottom along the ship's track.",

        "Marie Tharp, trained in geology and mathematics and employed at Columbia University's geology laboratory, was given the task of converting those slices into a single picture. Working from profiles and sounding values, she drew the North Atlantic floor by hand, aligning each ship's track against its neighbours, filling the gaps by interpolation and choosing how to render slopes at a vertical exaggeration that would make them legible on paper. The resulting physiographic diagram, published in 1957, was the first attempt to show the seafloor as terrain rather than as depth figures.",

        "In the course of the work she noticed something that had not been expected. The middle of the Mid Atlantic Ridge, a chain of underwater mountains running the length of the ocean, was not a ridge at all at its crest: it was split by a continuous valley. Her colleague Bruce Heezen initially dismissed the finding, on the grounds that the feature was probably an artefact of the sounding data, and the dismissal was not gentle. Tharp redrew the section several times, and the valley survived every redrawing. When the profiles were checked against new surveys it became clear that the rift was real and that it ran the length of the ridge system.",

        "The rift valley turned out to be the place where the ocean floor is being pulled apart, and the discovery gave a physical location to the idea of seafloor spreading, which became one of the foundations of plate tectonics. The map itself circulated as a printed sheet, in a period when most geological illustration was printed and pinned to a wall, and it was used for decades in classrooms. It is worth noting that the interpretation it carried was resisted twice over, once because the data were thought too noisy to trust and once because the person drawing them was a woman in a laboratory where that was unusual.",
      ],
    },
    questions: [
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "Why was the nineteenth century picture of the seabed so poor?",
        options: [
          "Nobody believed the ocean had a floor.",
          "The only sampling method was slow and unreliable.",
          "Ships refused to sail in deep water.",
          "The Challenger expedition measurements were lost.",
        ],
        answer: "The only sampling method was slow and unreliable.",
        evidence: { paragraph: "A", quote: "a slow method that a rolling ship could ruin" },
        trap: "out_of_scope",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "What advantage did the echo sounder bring?",
        options: [
          "It measured temperature as well as depth.",
          "It produced a continuous profile along the ship's route.",
          "It worked without a ship.",
          "It removed the need for interpolation.",
        ],
        answer: "It produced a continuous profile along the ship's route.",
        evidence: { paragraph: "B", quote: "record a continuous profile of the bottom as it steamed" },
        trap: "partly_true",
      },
      {
        type: "multiple_choice",
        group: "mcq",
        instruction: "Choose the correct letter, A, B, C or D.",
        stem: "How did Tharp's colleague first respond to the rift valley?",
        options: [
          "He published it immediately.",
          "He asked her to redraw the section.",
          "He rejected it as a likely fault in the data.",
          "He suggested the valley was a shipping channel.",
        ],
        answer: "He rejected it as a likely fault in the data.",
        evidence: { paragraph: "D", quote: "dismissed the finding, on the grounds that the feature was probably an artefact of the sounding data" },
        trap: "partly_true",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "The Challenger expedition took the first systematic soundings across ____ oceans.",
        answer: "three",
        evidence: { paragraph: "A", quote: "soundings across three oceans" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "The echo sounder measures the time a pulse of ____ takes to reach the seabed and return.",
        answer: "sound",
        evidence: { paragraph: "B", quote: "the time a pulse of sound takes to travel" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "The diagram was published in ____.",
        answer: "1957",
        evidence: { paragraph: "C", quote: "published in 1957" },
        trap: "none",
      },
      {
        type: "sentence_completion",
        group: "sentences",
        instruction: "Complete the sentences. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "The rift valley marked the place where the ocean floor is being pulled ____.",
        answer: "apart",
        evidence: { paragraph: "E", quote: "the place where the ocean floor is being pulled apart" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Tharp was the first person to show the seafloor as terrain rather than as depth figures.",
        answer: "TRUE",
        evidence: { paragraph: "C", quote: "the first attempt to show the seafloor as terrain rather than as depth figures" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "The rift valley disappeared when the section was redrawn.",
        answer: "FALSE",
        evidence: { paragraph: "D", quote: "the valley survived every redrawing" },
        trap: "negation_missed",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Tharp drew the map without the help of any colleague.",
        answer: "NOT GIVEN",
        evidence: { paragraph: "C", quote: "she drew the North Atlantic floor by hand" },
        trap: "over_inference",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "The published map was used in teaching for many years.",
        answer: "TRUE",
        evidence: { paragraph: "E", quote: "used for decades in classrooms" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        stem: "Which seafloor feature did Tharp find at the crest of the Mid Atlantic Ridge?",
        answer: "a continuous valley",
        alternatives: ["continuous valley", "a rift valley"],
        evidence: { paragraph: "D", quote: "it was split by a continuous valley" },
        trap: "word_limit",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Choose NO MORE THAN THREE WORDS from the passage for each answer.",
        stem: "Which theory did the discovery help to establish?",
        answer: "seafloor spreading",
        alternatives: ["the theory of seafloor spreading"],
        evidence: { paragraph: "E", quote: "gave a physical location to the idea of seafloor spreading" },
        trap: "none",
      },
    ],
  },

  {
    id: "P-soil",
    passage: {
      title: "The quiet engine in the soil",
      standfirst: "What fungi do for plants, and what the evidence does not yet show",
      wordCount: 649,
      paragraphs: [
        "Almost every plant on land is partnered with a fungus. The partnership is called a mycorrhiza, and it is not a rare condition: the great majority of plant species form one, and the relationship is old enough that it appears in the fossil record alongside the earliest land plants. The deal is straightforward in outline. The fungus grows a network of fine filaments through the soil, far finer than any root hair, and hands the plant water and mineral nutrients it has scavenged. The plant hands back sugars made in its leaves. Both sides appear to gain, which is why the association has persisted for hundreds of millions of years.",

        "There are two broad kinds. Ectomycorrhizal fungi wrap themselves around the short roots of trees such as oak, pine and birch, and are the ones that produce mushrooms in a forest in autumn. Arbuscular mycorrhizal fungi enter the cells of the root, where they form branched structures that exchange material directly with the plant, and they are found with most crops and most grasses. A single teaspoon of ordinary soil can contain several metres of fungal filament, and the network extends the effective reach of a root system by orders of magnitude.",

        "The fungus does more than find water. It mobilises phosphorus, an element that plants need and that is often locked up in soil particles where roots cannot get at it. In soils low in phosphorus the benefit to the plant is large and easy to measure; in soils that have been heavily fertilised the benefit shrinks or disappears, because the plant can take what it needs directly. This dependence on circumstance runs through the whole subject and is the reason confident general statements about mycorrhizae are unwise.",

        "A more dramatic claim emerged in the 1990s, when experiments using labelled carbon suggested that trees of different species could be linked by a shared fungal network, and that carbon could pass from one tree to another along it. The image of a cooperative forest, sometimes called the wood wide web, entered popular science and the public imagination, and it has been enormously attractive as an idea. The difficulty is that the experiments are hard to control. Fungi are everywhere in forest soil, and a labelled carbon atom found in a neighbouring tree may have travelled through a fungal link, or through decaying roots, or through the soil solution, or by several routes at once.",

        "Recent reviews of the published work have been sharply sceptical. They point out that the networks are less universal and less connected than the popular account implies, that competition between fungi is at least as important as cooperation, and that claims of trees deliberately feeding one another go well beyond what the measurements support. They do not argue that mycorrhizae are unimportant; the nutrient exchange between a fungus and its plant partner is real and well established. What they question is the transfer of the finding from a laboratory system to a forest floor, and the addition of intent to a relationship that can be explained by each partner pursuing its own interests.",
      ],
    },
    questions: [
      {
        type: "matching_headings",
        group: "headings",
        instruction: "Choose the correct heading for each of paragraphs A to E from the list of headings below.",
        stem: "Paragraph A",
        options: [
          "A partnership that is almost universal",
          "The two main forms the partnership takes",
          "A benefit that depends on the soil",
          "A popular idea that outran the evidence",
          "What critics of the popular account question",
          "How forests compete for water",
        ],
        answer: "A partnership that is almost universal",
        evidence: { paragraph: "A", quote: "Almost every plant on land is partnered with a fungus" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction: "Choose the correct heading for each of paragraphs A to E from the list of headings below.",
        stem: "Paragraph B",
        options: [
          "A partnership that is almost universal",
          "The two main forms the partnership takes",
          "A benefit that depends on the soil",
          "A popular idea that outran the evidence",
          "What critics of the popular account question",
          "How forests compete for water",
        ],
        answer: "The two main forms the partnership takes",
        evidence: { paragraph: "B", quote: "There are two broad kinds" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction: "Choose the correct heading for each of paragraphs A to E from the list of headings below.",
        stem: "Paragraph C",
        options: [
          "A partnership that is almost universal",
          "The two main forms the partnership takes",
          "A benefit that depends on the soil",
          "A popular idea that outran the evidence",
          "What critics of the popular account question",
          "How forests compete for water",
        ],
        answer: "A benefit that depends on the soil",
        evidence: { paragraph: "C", quote: "This dependence on circumstance runs through the whole subject" },
        trap: "partly_true",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction: "Choose the correct heading for each of paragraphs A to E from the list of headings below.",
        stem: "Paragraph D",
        options: [
          "A partnership that is almost universal",
          "The two main forms the partnership takes",
          "A benefit that depends on the soil",
          "A popular idea that outran the evidence",
          "What critics of the popular account question",
          "How forests compete for water",
        ],
        answer: "A popular idea that outran the evidence",
        evidence: { paragraph: "D", quote: "entered popular science and the public imagination" },
        trap: "none",
      },
      {
        type: "matching_headings",
        group: "headings",
        instruction: "Choose the correct heading for each of paragraphs A to E from the list of headings below.",
        stem: "Paragraph E",
        options: [
          "A partnership that is almost universal",
          "The two main forms the partnership takes",
          "A benefit that depends on the soil",
          "A popular idea that outran the evidence",
          "What critics of the popular account question",
          "How forests compete for water",
        ],
        answer: "What critics of the popular account question",
        evidence: { paragraph: "E", quote: "What they question is the transfer of the finding from a laboratory system to a forest floor" },
        trap: "out_of_scope",
      },
      {
        type: "ynng",
        group: "ynng",
        instruction: "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
        stem: "The writer believes the popular account of a cooperative forest goes further than the measurements allow.",
        answer: "YES",
        evidence: { paragraph: "E", quote: "claims of trees deliberately feeding one another go well beyond what the measurements support" },
        trap: "none",
      },
      {
        type: "ynng",
        group: "ynng",
        instruction: "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
        stem: "The writer thinks the nutrient exchange between a fungus and its plant partner is still unproven.",
        answer: "NO",
        evidence: { paragraph: "E", quote: "the nutrient exchange ... is real and well established" },
        trap: "negation_missed",
      },
      {
        type: "ynng",
        group: "ynng",
        instruction: "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
        stem: "The writer believes that fungal networks are more important than competition between fungi.",
        answer: "NOT GIVEN",
        evidence: { paragraph: "E", quote: "competition between fungi is at least as important as cooperation" },
        trap: "over_inference",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "The fungus receives ____ (9) made by the plant's leaves.",
        answer: "sugars",
        evidence: { paragraph: "A", quote: "The plant hands back sugars made in its leaves" },
        trap: "none",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "Fungi of the ectomycorrhizal kind wrap around the short ____ (10) of trees such as oak and pine.",
        answer: "roots",
        evidence: { paragraph: "B", quote: "wrap themselves around the short roots of trees" },
        trap: "none",
      },
      {
        type: "summary_completion",
        group: "summary",
        instruction: "Complete the summary. Choose ONE WORD ONLY from the passage for each answer.",
        stem: "On heavily fertilised land the benefit to the plant becomes smaller or ____ (11).",
        answer: "disappears",
        evidence: { paragraph: "C", quote: "the benefit shrinks or disappears" },
        trap: "form_shift",
      },
      {
        type: "matching_features",
        group: "features",
        instruction: "Match each statement with the correct item.",
        stem: "It forms branched structures inside the cells of a root.",
        options: ["ectomycorrhizal fungi", "arbuscular mycorrhizal fungi"],
        answer: "arbuscular mycorrhizal fungi",
        evidence: { paragraph: "B", quote: "enter the cells of the root, where they form branched structures" },
        trap: "none",
      },
      {
        type: "matching_features",
        group: "features",
        instruction: "Match each statement with the correct item.",
        stem: "It is associated with the mushrooms seen in an autumn forest.",
        options: ["ectomycorrhizal fungi", "arbuscular mycorrhizal fungi"],
        answer: "ectomycorrhizal fungi",
        evidence: { paragraph: "B", quote: "are the ones that produce mushrooms in a forest in autumn" },
        trap: "none",
      },
    ],
  },

  {
    id: "P-time",
    passage: {
      title: "The day of two noons",
      standfirst: "How railways forced the world to agree on the hour",
      wordCount: 652,
      paragraphs: [
        "Until the middle of the nineteenth century, every town kept its own time, set by the sun. Noon was when the sun crossed the local meridian, and a place a few dozen kilometres to the west reached noon a few minutes later. For most purposes this was not a problem, because travel was slow enough that a minute or two made no difference. A stagecoach could not carry a timetable that depended on anything finer.",

        "The railway ended that tolerance. A train running between two towns whose clocks disagreed by twelve minutes could not have a single printed departure time that was correct at both ends, and the consequences were practical: missed connections, and, in the worst recorded cases, collisions where two trains occupied the same single track because the crews disagreed about the time. Railroad companies in Britain began to run their services on a single standard from the 1840s, derived from the observatory at Greenwich, and the practice spread through the network long before the law caught up with it. Local clock time survived in some places into the 1850s, giving towns two times at once, and the newspapers called the resulting confusion the day of two noons.",

        "The legal change followed the practical one. Britain adopted Greenwich mean time as the legal time of the whole country in 1880, well after the railways had been using it for a generation. In North America the railways went further and invented a system of their own: on the eighteenth of November 1883, the continent's railroads jointly moved to five standard zones, and many towns adjusted their clocks to match, some of them doing so at noon on the day. The United States government did not legislate a national standard time until 1918.",

        "The choice of which meridian should be the world's zero was settled at an international conference held in Washington in 1884. Greenwich was already in use by the majority of the world's shipping, which was the decisive argument, and the conference resolved that the prime meridian should run through it and that longitude should be counted east and west from there. France, which had its own observatory and its own reasons, abstained and continued to keep Paris time for another twenty seven years. What the conference did not attempt was to decide what the time should be inside any country; that remained, and remains, a matter for governments.",

        "The consequence is that the map of time zones is a political document as much as an astronomical one. Zones follow national borders where they can, so that a country has one clock even if its shape spans several hours of sun; China is the largest example, and its western provinces keep the same hour as Beijing, which means that in parts of the country the sun is highest at three in the afternoon. Some zones are shifted by fractions of an hour: Nepal differs from India by fifteen minutes, and India itself by half an hour from the zones on either side. Spain sits on the western edge of Europe and keeps central European time, an inheritance from a decision taken in the 1940s. Even the length of the day is negotiable, since more than half the world's countries move their clocks twice a year and the rest, increasingly, do not.",
      ],
    },
    questions: [
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
        stem: "a case in which a disagreement about time contributed to a serious accident",
        options: ["A", "B", "C", "D", "E"],
        answer: "B",
        evidence: { paragraph: "B", quote: "collisions where two trains occupied the same single track because the crews disagreed about the time" },
        trap: "none",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
        stem: "a country that declined to adopt the agreed meridian for a time",
        options: ["A", "B", "C", "D", "E"],
        answer: "D",
        evidence: { paragraph: "D", quote: "France ... abstained and continued to keep Paris time for another twenty seven years" },
        trap: "none",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
        stem: "the year in which a national government first legislated a standard time",
        options: ["A", "B", "C", "D", "E"],
        answer: "C",
        evidence: { paragraph: "C", quote: "did not legislate a national standard time until 1918" },
        trap: "number_shift",
      },
      {
        type: "matching_information",
        group: "info",
        instruction: "Which paragraph contains the following information? Write the correct letter A to E. You may use any letter more than once.",
        stem: "why local solar time was good enough before the railway",
        options: ["A", "B", "C", "D", "E"],
        answer: "A",
        evidence: { paragraph: "A", quote: "travel was slow enough that a minute or two made no difference" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Railways in Britain ran on a single standard derived from the observatory at ____ (5).",
        answer: "Greenwich",
        evidence: { paragraph: "B", quote: "derived from the observatory at Greenwich" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "Greenwich mean time became the legal time of Britain in ____ (6).",
        answer: "1880",
        evidence: { paragraph: "C", quote: "as the legal time of the whole country in 1880" },
        trap: "number_shift",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "North American railroads moved to five standard ____ (7) in November 1883.",
        answer: "zones",
        evidence: { paragraph: "C", quote: "moved to five standard zones" },
        trap: "none",
      },
      {
        type: "note_completion",
        group: "notes",
        instruction: "Complete the notes. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.",
        stem: "At the 1884 conference the decisive argument for Greenwich was its use by the world's ____ (8).",
        answer: "shipping",
        evidence: { paragraph: "D", quote: "already in use by the majority of the world's shipping" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "The law in Britain recognised Greenwich mean time before the railways began using it.",
        answer: "FALSE",
        evidence: { paragraph: "C", quote: "well after the railways had been using it for a generation" },
        trap: "reversed_logic",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "The 1884 conference decided what the time should be inside each country.",
        answer: "FALSE",
        evidence: { paragraph: "D", quote: "What the conference did not attempt was to decide what the time should be inside any country" },
        trap: "negation_missed",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "India's time differs from neighbouring zones by half an hour.",
        answer: "TRUE",
        evidence: { paragraph: "E", quote: "India itself by half an hour from the zones on either side" },
        trap: "none",
      },
      {
        type: "tfng",
        group: "tfng",
        instruction: "Do the following statements agree with the information in the passage? Write TRUE, FALSE or NOT GIVEN.",
        stem: "Most countries in the world now change their clocks twice a year.",
        answer: "TRUE",
        evidence: { paragraph: "E", quote: "more than half the world's countries move their clocks twice a year" },
        trap: "over_generalisation",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "Which country keeps a single clock across several hours of sun?",
        answer: "China",
        evidence: { paragraph: "E", quote: "China is the largest example" },
        trap: "none",
      },
      {
        type: "short_answer",
        group: "short",
        instruction: "Answer the questions. Choose NO MORE THAN TWO WORDS from the passage for each answer.",
        stem: "What are the zones called because their boundaries follow national borders?",
        answer: "political document",
        alternatives: ["a political document"],
        evidence: { paragraph: "E", quote: "the map of time zones is a political document as much as an astronomical one" },
        trap: "out_of_scope",
      },
    ],
  },
];
