import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";

import { MODULES, READING_SCALE, LISTENING_SCALE } from "../content";
import { api, useSession, type AnalyticsResponse, type AttemptSummary } from "../lib/session";
import { BandSeries } from "../components/charts";
import { CefrPanel, PriorityList, ProgressMeter, TargetSetter, TipList } from "../components/progress";
import { EmptyState } from "../components/test-ui";
import {
  MODULE_LABELS,
  MeasureNote,
  PageHeader,
  SiteFooter,
  SiteNav,
  formatBand,
  formatDate,
  formatDuration,
  moduleIcon,
} from "../components/ui";

export const Route = createFileRoute("/analytics")({
  component: AnalyticsRoute,
});

function AnalyticsRoute() {
  const navigate = useNavigate();
  const { user, loading, setProfile } = useSession();
  const [analytics, setAnalytics] = useState<AnalyticsResponse | null>(null);
  const [attempts, setAttempts] = useState<AttemptSummary[]>([]);

  const load = useCallback(async () => {
    const [stats, list] = await Promise.all([
      api<AnalyticsResponse>("analytics/get"),
      api<{ attempts: AttemptSummary[] }>("practice/list"),
    ]);
    setAnalytics(stats);
    setAttempts(list.attempts);
  }, []);

  useEffect(() => {
    if (loading) return;
    if (!user) {
      void navigate({ to: "/account" });
      return;
    }
    void load();
  }, [loading, user, navigate, load]);

  const hasData = Boolean(analytics && analytics.totals.attempts > 0);

  return (
    <div>
      <SiteNav />
      <main className="mx-auto max-w-[1180px] px-5 py-12">
        <PageHeader
          eyebrow="Analytics"
          title="Section scores, error patterns and the time you spend."
          lede="One dashboard across all four modules. Every figure here comes from an attempt that was actually marked."
        />

        {analytics ? (
          <>
            <section className="mt-10 grid gap-px border border-rule bg-rule md:grid-cols-4">
              <Metric label="Attempts marked" value={String(analytics.totals.attempts)} note="all modules" />
              <Metric label="Minutes under the timer" value={String(analytics.totals.minutes)} note="locked countdowns" />
              <Metric label="Questions answered" value={String(analytics.totals.questionsAnswered)} note="Reading and Listening" />
              <Metric
                label="Marks lost"
                value={String(analytics.totals.mistakes)}
                note="filed in the Mistake Lab"
                tone="wrong"
              />
            </section>

            <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
              <div className="border border-rule bg-paper-raised p-5">
                <ProgressMeter
                  obtained={analytics.obtained}
                  target={analytics.targetBand}
                  progress={analytics.progress}
                />
              </div>
              <div className="space-y-6">
                {analytics.cefr ? <CefrPanel band={analytics.obtained} /> : null}
                <div className="border border-rule bg-paper-raised p-5">
                  <TargetSetter
                    value={analytics.targetBand}
                    onChange={(band) => {
                      void setProfile({ targetBand: band }).then(load);
                    }}
                  />
                </div>
              </div>
            </div>

            <section className="mt-12 grid gap-10 lg:grid-cols-2">
              <div>
                <div className="border-b border-rule pb-3">
                  <h2 className="text-xl font-semibold tracking-tight">
                    Areas that need more practice
                  </h2>
                  <p className="mt-2 max-w-[70ch] text-sm leading-relaxed text-ink-soft">
                    Ordered by the marks each question type has cost you. Drill the worst one before
                    sitting another full paper.
                  </p>
                </div>
                <div className="mt-4">
                  <PriorityList areas={analytics.areas} limit={6} />
                </div>
              </div>
              <div>
                <div className="border-b border-rule pb-3">
                  <h2 className="text-xl font-semibold tracking-tight">Tips that come from your errors</h2>
                  <p className="mt-2 max-w-[70ch] text-sm leading-relaxed text-ink-soft">
                    Every tip below is generated by a trap that has taken marks from you.
                  </p>
                </div>
                <div className="mt-4">
                  <TipList traps={analytics.traps} limit={5} />
                </div>
              </div>
            </section>

            {!hasData ? (
              <div className="mt-10">
                <EmptyState
                  title="No marked attempt yet"
                  body="Analytics fills in as you finish mocks. Reset Test draws a mock at random, so start with whichever module you want measured first."
                />
              </div>
            ) : null}

            <section className="mt-12 grid gap-6 lg:grid-cols-2">
              {analytics.modules.map((summary) => (
                <div key={summary.module} className="border border-rule bg-paper-raised p-5">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <span className="text-ink">{moduleIcon(summary.module, "h-5 w-5")}</span>
                      <h2 className="text-lg font-semibold tracking-tight">
                        {MODULE_LABELS[summary.module]}
                      </h2>
                    </div>
                    <span
                      className={
                        "bw-numeric text-xs " +
                        (summary.trend === "up"
                          ? "text-correct"
                          : summary.trend === "down"
                            ? "text-wrong"
                            : "text-ink-mute")
                      }
                    >
                      {summary.trend === "none" ? "no attempts" : summary.trend}
                    </span>
                  </div>

                  {summary.attempts === 0 ? (
                    <p className="mt-4 text-sm text-ink-soft">
                      Nothing marked yet.{" "}
                      <Link to="/test/$module" params={{ module: summary.module }} className="text-accent hover:underline">
                        Start a mock
                      </Link>
                      .
                    </p>
                  ) : (
                    <>
                      <div className="mt-4 grid grid-cols-3 gap-4">
                        <SmallStat label="Best" value={formatBand(summary.best)} />
                        <SmallStat label="Latest" value={formatBand(summary.latest)} />
                        <SmallStat label="Average" value={formatBand(summary.average)} />
                      </div>
                      <div className="mt-5">
                        <BandSeries
                          series={summary.series}
                          label={MODULE_LABELS[summary.module]}
                          target={analytics.targetBand}
                        />
                      </div>
                      <MeasureNote>
                        {summary.attempts} attempt{summary.attempts === 1 ? "" : "s"} ·{" "}
                        {summary.series.length} plotted
                      </MeasureNote>
                    </>
                  )}
                </div>
              ))}
            </section>

            {analytics.traps.length > 0 ? (
              <section className="mt-12">
                <div className="border-b border-rule pb-3">
                  <h2 className="text-xl font-semibold tracking-tight">Error pattern over time</h2>
                  <p className="mt-2 max-w-[80ch] text-sm leading-relaxed text-ink-soft">
                    Grouped by the reason the mark was lost, across every attempt you have finished.
                  </p>
                </div>
                <div className="mt-4 divide-y divide-rule">
                  {analytics.traps.map((trap) => (
                    <div key={trap.trap ?? "unclassified"} className="py-4">
                      <div className="flex flex-wrap items-baseline justify-between gap-3">
                        <p className="text-sm font-semibold">{trap.label}</p>
                        <p className="bw-numeric text-sm text-ink-soft">{trap.count}</p>
                      </div>
                      <p className="mt-1.5 max-w-[90ch] text-sm leading-relaxed text-ink-soft">
                        {trap.coaching}
                      </p>
                    </div>
                  ))}
                </div>
              </section>
            ) : null}

            {analytics.types.length > 0 ? (
              <section className="mt-12">
                <div className="border-b border-rule pb-3">
                  <h2 className="text-xl font-semibold tracking-tight">Accuracy by task type</h2>
                  <p className="mt-2 max-w-[80ch] text-sm leading-relaxed text-ink-soft">
                    Where your accuracy is lowest, the questions are not harder; they are asking for a
                    different reading behaviour.
                  </p>
                </div>
                <div className="mt-4 overflow-x-auto">
                  <table className="w-full border-collapse text-sm">
                    <thead>
                      <tr className="border-b border-rule-strong">
                        <th className="bw-label py-2.5 text-left text-ink-mute">Task type</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Correct</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Seen</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Accuracy</th>
                      </tr>
                    </thead>
                    <tbody>
                      {analytics.types.map((row) => (
                        <tr key={row.type} className="border-b border-rule last:border-0">
                          <td className="py-3">{row.type.replace(/_/g, " ")}</td>
                          <td className="bw-numeric py-3 text-right">{row.correct}</td>
                          <td className="bw-numeric py-3 text-right">{row.total}</td>
                          <td
                            className={
                              "bw-numeric py-3 text-right " +
                              (row.rate >= 70 ? "text-correct" : row.rate >= 50 ? "text-ink" : "text-wrong")
                            }
                          >
                            {row.rate}%
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </section>
            ) : null}

            <section className="mt-12">
              <div className="border-b border-rule pb-3">
                <h2 className="text-xl font-semibold tracking-tight">History over time</h2>
                <p className="mt-2 max-w-[80ch] text-sm leading-relaxed text-ink-soft">
                  Every marked attempt in order, with the distance to your target at the time it was
                  taken. A column that stays negative is the one to work on.
                </p>
              </div>

              {attempts.length === 0 ? (
                <div className="mt-6">
                  <EmptyState
                    title="No attempts recorded yet"
                    body="Take the level check or sit a full mock and the history starts here."
                  />
                </div>
              ) : (
                <div className="mt-4 overflow-x-auto">
                  <table className="w-full border-collapse text-sm">
                    <thead>
                      <tr className="border-b border-rule-strong">
                        <th className="bw-label py-2.5 text-left text-ink-mute">Date</th>
                        <th className="bw-label py-2.5 text-left text-ink-mute">Attempt</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Raw</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Band</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">Time</th>
                        <th className="bw-label py-2.5 text-right text-ink-mute">vs target</th>
                      </tr>
                    </thead>
                    <tbody>
                      {attempts.map((attempt) => {
                        const delta =
                          analytics.targetBand && attempt.band
                            ? Math.round((attempt.band - analytics.targetBand) * 2) / 2
                            : null;
                        return (
                          <tr key={attempt.id} className="border-b border-rule last:border-0">
                            <td className="bw-numeric py-3 text-ink-soft">{formatDate(attempt.finishedAt)}</td>
                            <td className="py-3">
                              <Link
                                to="/review/$attemptId"
                                params={{ attemptId: attempt.id }}
                                className="text-accent hover:underline"
                              >
                                {attempt.kind === "diagnostic"
                                  ? "Level check"
                                  : attempt.kind === "drill"
                                    ? "Focused drill"
                                    : `${MODULE_LABELS[attempt.module]} · ${attempt.mockTitle}`}
                              </Link>
                            </td>
                            <td className="bw-numeric py-3 text-right text-ink-soft">
                              {attempt.total ? `${attempt.rawScore ?? 0}/${attempt.total}` : "—"}
                            </td>
                            <td className="bw-numeric py-3 text-right font-semibold">
                              {formatBand(attempt.band)}
                            </td>
                            <td className="bw-numeric py-3 text-right text-ink-soft">
                              {formatDuration(attempt.durationSec)}
                            </td>
                            <td
                              className={
                                "bw-numeric py-3 text-right " +
                                (delta === null
                                  ? "text-ink-mute"
                                  : delta >= 0
                                    ? "text-correct"
                                    : "text-wrong")
                              }
                            >
                              {delta === null ? "set a target" : `${delta > 0 ? "+" : ""}${delta.toFixed(1)}`}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </section>

            <section className="mt-12 grid gap-6 lg:grid-cols-2">
              <div className="border border-rule bg-paper-raised p-5">
                <p className="bw-label text-ink-mute">The scales in use</p>
                <p className="mt-3 text-sm leading-relaxed text-ink-soft">
                  Reading and Listening convert a raw mark out of 40. The published conversions used
                  here are shown in full so you can check any band this app reports.
                </p>
                <div className="mt-4 grid gap-4 sm:grid-cols-2">
                  <ScaleList title="Reading" steps={READING_SCALE} />
                  <ScaleList title="Listening" steps={LISTENING_SCALE} />
                </div>
              </div>
              <div className="border border-rule bg-paper-raised p-5">
                <p className="bw-label text-ink-mute">Next practice</p>
                <p className="mt-3 text-sm leading-relaxed text-ink-soft">
                  {analytics.weakestModule
                    ? `Your lowest latest band is in ${MODULE_LABELS[analytics.weakestModule]}. A weak module drags the overall estimate down more than a strong one lifts it, so balance the profile before pushing a favourite module higher.`
                    : "Complete at least two modules and the engine will name the one to work on."}
                </p>
                <div className="mt-4 flex flex-wrap gap-2">
                  {MODULES.map((module) => (
                    <Link
                      key={module.id}
                      to="/test/$module"
                      params={{ module: module.id }}
                      className="border border-rule-strong px-3.5 py-2 text-xs font-medium hover:border-ink"
                    >
                      {module.title}
                    </Link>
                  ))}
                </div>
              </div>
            </section>
          </>
        ) : (
          <div className="py-24">
            <p className="bw-label text-ink-mute">Analytics</p>
            <p className="mt-3 text-lg font-medium">Reading your attempts…</p>
          </div>
        )}
      </main>
      <SiteFooter />
    </div>
  );
}

function Metric({
  label,
  value,
  note,
  tone,
}: {
  label: string;
  value: string;
  note: string;
  tone?: "wrong";
}) {
  return (
    <div className="bg-paper-raised p-5">
      <p className="bw-label text-ink-mute">{label}</p>
      <p className={"bw-numeric mt-2 text-3xl font-semibold " + (tone === "wrong" ? "text-wrong" : "")}>
        {value}
      </p>
      <p className="mt-1 text-xs text-ink-soft">{note}</p>
    </div>
  );
}

function SmallStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="border-t border-rule pt-3">
      <p className="bw-label text-ink-mute">{label}</p>
      <p className="bw-numeric mt-1 text-xl font-semibold">{value}</p>
    </div>
  );
}

function ScaleList({ title, steps }: { title: string; steps: { min: number; band: number }[] }) {
  return (
    <div>
      <p className="bw-label text-ink-mute">{title}</p>
      <ul className="mt-2 space-y-1">
        {steps.slice(0, 8).map((step) => (
          <li key={step.band} className="flex justify-between gap-4 text-xs text-ink-soft">
            <span className="bw-numeric">{step.min}+</span>
            <span className="bw-numeric">band {step.band}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
